composer.json, src/Validation/Rules/Email.php, tests/Validation/Rules/EmailTest.php
This adds a dependency (the same used by Symfony and Laravel) and exposes dependency classes as parameters to the attribute. Let me know if you want to make adjustments to any of that.
Related to #3.
=> Adds validator for email addresses.

composer.json, src/Validation/Rules/PhoneNumber.php, tests/Validation/Rules/PhoneNumberTest.php
@brendt - This adds a fairly hefty dependency, but I believe it might be worth it to support phone number validation natively.
Related to #3.
=> Adds phone number validator.

src/Validation/Rules/Between.php, tests/Validation/Rules/BetweenTest.php
Add Between validation rule and test related to #3
=> Added Between validation rule

src/Validation/Rules/ShouldBeFalse.php, src/Validation/Rules/ShouldBeTrue.php, tests/Validation/Rules/ShouldBeFalseTest.php, tests/Validation/Rules/ShouldBeTrueTest.php
Hi!
Regarding [Issue #3](https://github.com/tempestphp/tempest-framework/issues/3) this PR adds ShouldBeTrue and ShouldBeFalse validation rules and it's tests.
Let  me know if something must to be changed.
Thanks!
=> Add ShouldBeTrue and ShouldBeFalse validation rules

src/Validation/Rules/StartsWith.php, tests/Validation/Rules/StartsWithTest.php
As mentioned in https://github.com/tempestphp/tempest-framework/issues/3
=> Add StartsWith validation

src/Application/Kernel.php, src/Discovery/DiscoveryDiscovery.php, src/Validation/Rules/Enum.php, tests/Validation/Rules/EnumTest.php, tests/Validation/Rules/Fixtures/SomeBackedEnum.php, tests/Validation/Rules/Fixtures/SomeEnum.php, tests/bootstrap.php
This PR adds an enum validation rule (#3). This rule validates backed enums by their values or regular enums by their case name.
=> Adds enum validation rule

.github/CONTRIBUTING.md, .github/contributing.md, README.md
This PR adds a contributing file where we can flesh out some best practice surrounding validation rules, etc.
=> Adds a contributing file

src/Application/Kernel.php, src/Discovery/DiscoveryDiscovery.php, src/Validation/Rules/Regex.php, tests/Validation/Rules/RegexTest.php, tests/bootstrap.php
=> Adds regex validation rule

src/Validation/Rules/Boolean.php, tests/Validation/Rules/BooleanTest.php
This PR adds an boolean validation rule.
=> Adds boolean validation rule

src/Validation/Rules/MACAddress.php, tests/Validation/Rules/MACAddressTest.php
=> Validating MAC Address

.gitattributes
=> Adds .gitattributes

src/Validation/Rules/Timezone.php, tests/Validation/Rules/TimezoneTest.php
First ever open-source contribution :)
Let me know if you have any questions or requests about my changes.
Refers to https://github.com/tempestphp/tempest-framework/issues/3
=> Validating Timezones

src/Validation/Rules/IPAddress.php, tests/Validation/Rules/IPAddressTest.php
YAVR (Yet another validation rule) - addressing #3
=> Validating IP Address

src/Validation/Rules/Count.php, src/Validation/Rules/Length.php, tests/Validation/Rules/CountTest.php, tests/Validation/Rules/LengthTest.php
=> refactor: Improve length and count validation rules

app/Controllers/MiddlewareDependency.php, app/Controllers/TestController.php, app/Controllers/TestMiddleware.php, src/Http/GenericRouter.php, src/Http/Get.php, src/Http/HttpMiddleware.php, src/Http/Post.php, src/Http/Response.php, src/Http/Route.php, tests/Route/RouterTest.php
=> Add HTTP middleware support

.php-cs-fixer.dist.php, app/Controllers/TestMiddleware.php, app/Modules/Home/home.php, app/Views/base.php, app/Views/baseWithNamedSlot.php, app/Views/extendsWithNamedSlot.php, app/Views/extendsWithVariables.php, app/Views/include-child.php, app/Views/include-parent.php, app/Views/overview.php, app/Views/rawAndEscaping.php, app/Views/withViewModel.php, src/Application/Kernel.php, src/Console/Commands/DiscoveryClearCommand.php, src/Database/Migrations/CreateMigrationsTable.php, src/Mapper/ModelToQueryMapper.php, src/Mapper/QueryToModelMapper.php, src/Mapper/RequestToObjectMapper.php, src/Mapper/RequestToRequestMapper.php, src/Support/Reflection/Attributes.php, src/Validation/Exceptions/ValidationException.php, tests/Architecture/ArchitectureTest.php, tests/TestCase.php, tests/Unit/Application/ConsoleApplicationTest.php, tests/Unit/KernelTest.php
@brendt - I would appreciate a review here, as some of these are pretty opinionated and we haven't really been consistent in the past.
=> Adds namespace import rules

src/Container/ContainerLog.php, src/Container/Context.php, src/Container/Dependency.php, src/Container/Exceptions/CannotAutowireException.php, src/Container/Exceptions/CircularDependencyException.php, src/Container/GenericContainer.php, src/Container/InMemoryContainerLog.php, tests/Unit/Container/Exceptions/CannotAutowireExceptionTest.php, tests/Unit/Container/Exceptions/CircularDependencyExceptionTest.php, tests/Unit/Container/Fixtures/AutowireA.php, tests/Unit/Container/Fixtures/AutowireB.php, tests/Unit/Container/Fixtures/AutowireC.php, tests/Unit/Container/Fixtures/CircularA.php, tests/Unit/Container/Fixtures/CircularB.php, tests/Unit/Container/Fixtures/CircularC.php, tests/Unit/Container/Fixtures/CircularZ.php
=> Container log

README.md
Fixed the documentation to point to the "main" branch because "master" branch is now moved to the "main" branch.
=> Fixed the documentation to point to the "main" branch. 

src/Http/Session/CleanupSessionsCommand.php
=> Cleanup sessions periodically

src/Tempest/Console/composer.json
Sorry, missed this one in console component 😅
=> Replace `larapack/dd` with `symfony/var-dumper` in Console

.github/workflows/quality-assurance.yml, .github/workflows/quality-control.yml, src/Tempest/Support/PathHelper.php
We should have Windows in the test suite so we can ensure there are no issues there (see #273).
=> Adds Windows to the test suite

src/Tempest/Database/Migrations/CreateMigrationsTable.php, src/Tempest/Database/QueryStatements/AlterActionStatement.php, src/Tempest/Database/QueryStatements/AlterStatement.php, src/Tempest/Database/QueryStatements/AlterTableStatement.php, src/Tempest/Database/QueryStatements/BelongsToStatement.php, src/Tempest/Database/QueryStatements/ConstraintStatement.php, src/Tempest/Database/QueryStatements/CreateTableStatement.php, src/Tempest/Database/QueryStatements/DropTableStatement.php, src/Tempest/Database/QueryStatements/ForeignKeyStatement.php, src/Tempest/Database/QueryStatements/IndexStatement.php, src/Tempest/Database/QueryStatements/UniqueStatement.php, src/Tempest/Mapper/Mappers/ArrayToObjectMapper.php, src/Tempest/Support/Reflection/MethodReflector.php, tests/Fixtures/Migrations/CreateAuthorTable.php, tests/Fixtures/Migrations/CreateBookTable.php, tests/Integration/Database/QueryStatements/AlterTableStatementTest.php, tests/Integration/Database/QueryStatements/CreateUserMigration.php, tests/Integration/Database/QueryStatements/User.php, tests/Integration/Mapper/Fixtures/ObjectFactoryAMigration.php, tests/Integration/ORM/FooMigration.php, tests/Integration/ORM/Migrations/CreateATable.php, tests/Integration/ORM/Migrations/CreateBTable.php, tests/Integration/ORM/Migrations/CreateCTable.php, tests/Unit/Database/DatabaseQueryStatementTest.php
Currently a WIP pull request so I have a clear overview of the changes I have made so far
=> [WIP] alter table

src/Tempest/Clock/.gitattributes, src/Tempest/CommandBus/.gitattributes, src/Tempest/Container/.gitattributes, src/Tempest/Core/.gitattributes, src/Tempest/Database/.gitattributes, src/Tempest/Debug/.gitattributes, src/Tempest/EventBus/.gitattributes, src/Tempest/Http/.gitattributes, src/Tempest/HttpClient/.gitattributes, src/Tempest/Log/.gitattributes, src/Tempest/Mapper/.gitattributes, src/Tempest/Reflection/.gitattributes, src/Tempest/Support/.gitattributes, src/Tempest/Validation/.gitattributes, src/Tempest/View/.gitattributes
=> Adds sub-split gitattributes.

CHANGELOG.md, composer.json, src/Tempest/Console/src/Commands/DiscoveryCacheCommand.php, src/Tempest/Core/src/DiscoveryDiscovery.php, src/Tempest/Core/src/GenericExceptionHandlerSetup.php, src/Tempest/Core/src/HandlesDiscoveryCache.php, src/Tempest/Http/src/RouteDiscovery.php, tests/Integration/Console/Commands/MyDiscovery.php, tests/Integration/Framework/Commands/DiscoveryCacheCommandTest.php
=> Discovery cache command

composer.json, src/Tempest/Support/composer.json, src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/src/functions.php, src/Tempest/Support/tests/StringHelperTest.php, tests/Integration/Support/StringHelperTest.php
=> feat: refactor string helper to object

src/Tempest/Mapper/src/Mappers/ArrayToObjectMapper.php, src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/src/InvalidMapWithKeysUsage.php, src/Tempest/Support/src/IsIterable.php, src/Tempest/Support/src/LanguageHelper.php, src/Tempest/Support/src/OffsetDoesNotExist.php, src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/src/functions.php, src/Tempest/Support/tests/ArrayHelperTest.php, src/Tempest/Validation/src/Exceptions/ValidationException.php
=> feat: add array helper

src/Tempest/Console/src/Commands/TailDebugLogCommand.php, src/Tempest/Console/src/Commands/TailProjectLogCommand.php, src/Tempest/Console/src/Commands/TailServerLogCommand.php, src/Tempest/Console/src/Exceptions/ConsoleExceptionHandler.php, src/Tempest/Console/src/GenericConsole.php, src/Tempest/Console/src/Highlight/ConsoleHighlighterInitializer.php, src/Tempest/Console/src/Highlight/TempestConsoleLanguage/Injections/CommentInjection.php, src/Tempest/Console/src/Testing/ConsoleTester.php, src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/src/InvalidMapWithKeysUsage.php, src/Tempest/Support/tests/ArrayHelperTest.php
=> maintenance: tag console highlighter

src/Tempest/Support/src/StringHelper.php, src/Tempest/View/src/Elements/ElementFactory.php, src/Tempest/View/src/Elements/GenericElement.php, src/Tempest/View/src/IsView.php, src/Tempest/View/src/Renderers/TempestViewRenderer.php, src/Tempest/View/src/View.php, src/Tempest/View/src/ViewComponentView.php, tests/Fixtures/Views/view-component-attribute-without-this-a.view.php, tests/Fixtures/Views/view-component-attribute-without-this-b.view.php, tests/Fixtures/Views/view-component-with-camelcase-attribute-a.view.php, tests/Fixtures/Views/view-component-with-camelcase-attribute-b.view.php, tests/Fixtures/Views/view-component-with-non-self-closing-slot-a.view.php, tests/Fixtures/Views/view-component-with-non-self-closing-slot-b.view.php, tests/Fixtures/Views/view-defined-local-vars-a.view.php, tests/Fixtures/Views/view-defined-local-vars-b.view.php, tests/Integration/View/ViewComponentTest.php
=> fix: view component attribute fixes

src/Tempest/Console/src/Commands/InstallCommand.php, src/Tempest/Support/src/PathHelper.php, src/Tempest/Support/tests/PathHelperTest.php, tests/Integration/Console/Commands/InstallCommandTest.php
=> test(console): add test for install command

src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/tests/StringHelperTest.php
=> feat: add str::startswith and endswith

src/Tempest/Http/src/Static/StaticCleanCommand.php, src/Tempest/Http/src/Static/StaticGenerateCommand.php, tests/Integration/Http/Static/StaticCleanCommandTest.php, tests/Integration/Http/Static/StaticGenerateCommandTest.php
This would fix #478 
I wonder if there are any downsides to this approach?
=> feat: use directories instead of file names to allow default server config setup

src/Tempest/Core/src/Kernel/LoadDiscoveryClasses.php
=> fix: handle invalid discovery cache

src/Tempest/Clock/composer.json, src/Tempest/CommandBus/composer.json, src/Tempest/Console/composer.json, src/Tempest/Container/composer.json, src/Tempest/Core/composer.json, src/Tempest/Database/composer.json, src/Tempest/EventBus/composer.json, src/Tempest/Http/composer.json, src/Tempest/HttpClient/composer.json, src/Tempest/Log/composer.json, src/Tempest/Mapper/composer.json, src/Tempest/Reflection/composer.json, src/Tempest/Support/composer.json, src/Tempest/Validation/composer.json, src/Tempest/View/composer.json
Hi!
Regarding [Issue #423](https://github.com/tempestphp/tempest-framework/issues/423) this PR adds specific description for each component composer file.
Please let me know if anything needs to be changed as I don't have a full understanding of each of their responsibilities.
Thanks!
=> Add components composer file descriptions

src/Tempest/Database/src/Builder/Relations/HasOneRelation.php, src/Tempest/Database/src/Exceptions/InvalidRelation.php, src/Tempest/Database/src/HasOne.php, src/Tempest/Database/src/QueryStatements/BelongsToStatement.php, src/Tempest/Database/tests/DatabaseQueryStatementTest.php, src/Tempest/Database/tests/Relations/Fixtures/HasOneInvalidRelatedModel.php, src/Tempest/Database/tests/Relations/Fixtures/HasOneParentModel.php, src/Tempest/Database/tests/Relations/Fixtures/HasOneRelatedModel.php, src/Tempest/Database/tests/Relations/HasOneRelationTest.php, src/Tempest/Reflection/src/ClassReflector.php, tests/Integration/ORM/IsDatabaseModelTest.php, tests/Integration/ORM/Migrations/CreateHasManyThroughTable.php, tests/Integration/ORM/Models/ChildModel.php, tests/Integration/ORM/Models/ThroughModel.php
Fixes #508. Solved todo's in HasOneRelation.
- Added ability to add `HasOne` relation based on propertyName given in the `HasOne` tag
- Add exceptions for all not found cases with proper error message
=> feat: add named hasOne relation

src/Tempest/Validation/src/Validator.php, src/Tempest/Validation/tests/ValidatorTest.php
This pull request adds support for validating values using closures:
```php
$validator->validateValue('foo+1@gmail.com', function (mixed $value) {
if ((str_contains('@gmail.com', $value) && str_contains('+', $value)) {
return 'Gmail aliases are not allowed';
}
return true;
});
```
I've had this need when writing the release script and when working on the publish command. Writing a class was quite cumbersome in these situations.
I've opened a discussion about this, among other things, here: https://discord.com/channels/1236153076688359495/1294321824498323547
=> feat(validation): support validating by closure

src/Tempest/View/src/Elements/GenericElement.php, tests/Integration/View/TempestViewRendererTest.php
=> fix: view argument casing

src/Tempest/Http/src/HttpApplication.php
resolving `HttpApplication` via the container, and setting-up the `Singleton` attribute.
=> refactor(http): resolve `HttpApplication` via the container

src/Tempest/Container/src/AutowireDiscovery.php
@Jeroen-G 
I found a bug using the `#[Autowire]` feature while enabled discovery cache. Instead of caching the container `definitions` I introduced a separate array which holds the autowire mapping, put that in the discovery cache and re-add these to the container during cache recovery. 
- set `CACHE=true` in `.env`
- Run `php tempest cache:clear --all` for good measure
- Use my provided zip which includes which includes the steps below: [[autowire-example.zip](https://github.com/user-attachments/files/17530379/autowire-example.zip)]
- Create an interface
- Create a class which implements said class and add `#[Autowire]`
- Create a controller using the autowired interface
- Run `php tempest serve`
- See no error
Performing the same steps on the `main` branch will result in the following …
=> fix(container): fix caching of autowire discovered classes

src/Tempest/Auth/src/AuthConfig.php, src/Tempest/Auth/src/AuthInstaller.php, src/Tempest/Auth/src/Install/Permission.php, src/Tempest/Auth/src/Install/PermissionMigration.php, src/Tempest/Auth/src/Install/User.php, src/Tempest/Auth/src/Install/UserMigration.php, src/Tempest/Auth/src/Install/UserPermission.php, src/Tempest/Auth/src/Install/UserPermissionMigration.php, tests/Integration/Auth/AuthInstallerTest.php, tests/Integration/Auth/AuthorizerTest.php, tests/Integration/Auth/Fixtures/CustomAuthorizer.php, tests/Integration/Auth/SessionAuthenticatorTest.php, tests/Integration/Auth/UserModelTest.php
=> chore: auth improvements

src/Tempest/Support/src/ArrayHelper.php, tests/Integration/Support/ArrayHelperTest.php
Implemented `sort` method for `ArrayHelper`.
This sorts the array in ascending order.
#631
=> feat (ArrayHelper): implement sort method.

src/Tempest/Core/src/Kernel/LoadDiscoveryLocations.php
=> fix(core): discovery location loading order

src/Tempest/Http/src/Get.php, src/Tempest/Http/src/Post.php, src/Tempest/Http/src/Route.php, src/Tempest/Http/src/RouteDiscovery.php, tests/Fixtures/Controllers/ControllerWithRepeatedRoutes.php, tests/Integration/Route/RouterTest.php
=> feat: multiple routes per controller method

src/Tempest/Auth/src/AuthorizerMiddleware.php, src/Tempest/CommandBus/src/CommandBusMiddleware.php, src/Tempest/CommandBus/src/CommandBusMiddlewareCallable.php, src/Tempest/CommandBus/src/GenericCommandBus.php, src/Tempest/Console/src/Actions/ExecuteConsoleCommand.php, src/Tempest/Console/src/ConsoleMiddleware.php, src/Tempest/Console/src/ConsoleMiddlewareCallable.php, src/Tempest/Console/src/Middleware/CautionMiddleware.php, src/Tempest/Console/src/Middleware/ConsoleExceptionMiddleware.php, src/Tempest/Console/src/Middleware/ForceMiddleware.php, src/Tempest/Console/src/Middleware/HelpMiddleware.php, src/Tempest/Console/src/Middleware/InvalidCommandMiddleware.php, src/Tempest/Console/src/Middleware/OverviewMiddleware.php, src/Tempest/Console/src/Middleware/ResolveOrRescueMiddleware.php, src/Tempest/EventBus/src/EventBusMiddleware.php, src/Tempest/EventBus/src/EventBusMiddlewareCallable.php, src/Tempest/EventBus/src/GenericEventBus.php, src/Tempest/EventBus/tests/Fixtures/MyEventBusMiddleware.php, src/Tempest/Http/src/Cookie/SetCookieMiddleware.php, src/Tempest/Http/src/GenericRouter.php, src/Tempest/Http/src/HttpMiddleware.php, src/Tempest/Http/src/HttpMiddlewareCallable.php, tests/Fixtures/Controllers/TestGlobalMiddleware.php, tests/Fixtures/Controllers/TestMiddleware.php, tests/Integration/CommandBus/Fixtures/MyCommandBusMiddleware.php, tests/Integration/Console/Fixtures/SpecificMiddleware.php
=> feat: middleware callables

src/Tempest/Http/src/GenericRouter.php, tests/Fixtures/Controllers/UriGeneratorController.php, tests/Integration/Route/RouterTest.php
=> fix(http): collision between route and query params for uri generator

src/Tempest/Core/src/PublishesFiles.php, tests/Integration/Auth/AuthInstallerTest.php
=> fix(core): installers not updating docblock references

src/Tempest/View/src/Attributes/AttributeFactory.php, src/Tempest/View/src/Attributes/BooleanAttribute.php, src/Tempest/View/src/Elements/GenericElement.php, src/Tempest/View/src/Renderers/TempestViewCompiler.php, tests/Integration/View/TempestViewRendererDataPassingTest.php
=> feat(view): add boolean attributes

src/Tempest/Http/src/Commands/MakeRequestCommand.php, src/Tempest/Http/src/Stubs/RequestStub.php, tests/Integration/Http/MakeRequestCommandTest.php
This PR add the `make:request` command to generate a basic `Request` class
=> feat(console): add `make:request` command

src/Tempest/View/src/Components/Form.php, src/Tempest/View/src/Components/Input.php, src/Tempest/View/src/Components/Submit.php, src/Tempest/View/src/Elements/ElementFactory.php, src/Tempest/View/src/Elements/RawElement.php, tests/Integration/View/TempestViewRendererTest.php, tests/Integration/View/ViewComponentDiscoveryTest.php
This reverts commit df6a4189ae62d1ed3ea7fcf03f4d2cc1005c57db.
=> chore(view): revert raw html element (#737)

src/Tempest/Console/src/Actions/ExecuteConsoleCommand.php, src/Tempest/Console/src/Console.php, src/Tempest/Console/src/ConsoleApplication.php, src/Tempest/Console/src/ConsoleMiddleware.php, src/Tempest/Console/src/ConsoleMiddlewareCallable.php, src/Tempest/Console/src/Exceptions/ConsoleErrorHandler.php, src/Tempest/Console/src/ExitCode.php, src/Tempest/Console/src/GenericConsole.php, src/Tempest/Console/src/HasExitCode.php, src/Tempest/Console/src/InvalidExitCode.php, src/Tempest/Console/src/Middleware/CautionMiddleware.php, src/Tempest/Console/src/Middleware/ConsoleExceptionMiddleware.php, src/Tempest/Console/src/Middleware/ForceMiddleware.php, src/Tempest/Console/src/Middleware/HelpMiddleware.php, src/Tempest/Console/src/Middleware/InvalidCommandMiddleware.php, src/Tempest/Console/src/Middleware/OverviewMiddleware.php, src/Tempest/Console/src/Middleware/ResolveOrRescueMiddleware.php, tests/Integration/Console/Fixtures/SpecificMiddleware.php
Alternative to https://github.com/tempestphp/tempest-framework/pull/735
Closes https://github.com/tempestphp/tempest-framework/issues/729
=> refactor(console): exit codes as enum + int

src/Tempest/Http/src/Patch.php, src/Tempest/Http/src/Put.php, src/Tempest/Http/tests/Routing/Construction/RouteConfiguratorTest.php
Provide new attributes for `Put` and `Patch` methods
=> feat(http): add `Put` and `Patch` attributes

src/Tempest/Validation/src/Rules/ArrayList.php, src/Tempest/Validation/tests/Rules/ArrayListTest.php
This pull request adds support for validating array list.
=> feat(validation): `ArrayList` rule

src/Tempest/Validation/src/Rules/Enum.php, src/Tempest/Validation/tests/Rules/EnumTest.php
This PR adds:
- Supports varidic functions for only and expects
- Chainable only or expects
=> feat(validation): enhance enum validation

src/Tempest/Console/src/Initializers/SchedulerInitializer.php, src/Tempest/Console/src/Scheduler/GenericScheduler.php, src/Tempest/Console/src/Scheduler/SchedulerConfig.php, tests/Integration/Console/Scheduler/GenericSchedulerTest.php
=> feat(console): infer binary path for scheduler

src/Tempest/Core/src/Kernel.php
=> fix(core): do not redefine `TEMPEST_START`

composer.json, src/Tempest/View/src/Renderers/TwigConfig.php, src/Tempest/View/src/Renderers/TwigInitializer.php, src/Tempest/View/src/Renderers/TwigViewRenderer.php, tests/Integration/View/TwigViewRendererTest.php, tests/Integration/View/twig/base.twig, tests/Integration/View/twig/index.twig
Hi,
This pull request introduces the integration of Twig as a templating engine into the Tempest framework. Key changes include adding Twig dependencies, creating configuration and initialization classes, and implementing a Twig-based view renderer.
Resolved #707 
BONUS: https://speakerdeck.com/fabpot/symfonycon-vienna-2025-twig-still-relevant-in-2025 :)
=> feat(view): add twig support

src/Tempest/Console/src/Components/Interactive/SingleChoiceComponent.php, src/Tempest/Console/src/Console.php, src/Tempest/Console/src/ConsoleCommand.php, src/Tempest/Console/src/GenericConsole.php, src/Tempest/Console/src/Middleware/InvalidCommandMiddleware.php, src/Tempest/Console/src/Middleware/OverviewMiddleware.php, src/Tempest/Console/src/Middleware/ResolveOrRescueMiddleware.php, src/Tempest/Support/src/IsIterable.php, src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/tests/StringHelperTest.php, tests/Fixtures/Commands/HelloWorldTestCommand.php, tests/Integration/Console/Middleware/CautionMiddlewareTest.php, tests/Integration/Console/Middleware/ForceMiddlewareTest.php, tests/Integration/Console/Middleware/OverviewMiddlewareTest.php, tests/Integration/Console/Middleware/ResolveOrRescueMiddlewareTest.php
=> feat(console): several QOL improvements

src/Tempest/Console/src/Components/InteractiveComponentRenderer.php, src/Tempest/Mapper/src/functions.php, src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/tests/HtmlStringTest.php, src/Tempest/Support/tests/PathHelperTest.php
This PR fixes typos all over the codebase.
=> chore: fix typos

composer.json, src/Tempest/Core/src/functions.php, src/Tempest/Database/src/Builder/FieldName.php, src/Tempest/Database/src/Casters/RelationCaster.php, src/Tempest/Database/src/DatabaseModel.php, src/Tempest/Database/src/Mappers/QueryToModelMapper.php, src/Tempest/Mapper/src/Casters/CasterFactory.php, src/Tempest/Mapper/src/Casters/ObjectCaster.php, src/Tempest/Reflection/src/ClassReflector.php, src/Tempest/Reflection/src/HasAttributes.php, src/Tempest/Reflection/tests/ClassReflectorTest.php, src/Tempest/Reflection/tests/Fixtures/ChildWithRecursiveAttribute.php, src/Tempest/Reflection/tests/Fixtures/ClassWithInterfaceWithRecursiveAttribute.php, src/Tempest/Reflection/tests/Fixtures/InterfaceWithRecursiveAttribute.php, src/Tempest/Reflection/tests/Fixtures/ParentWithRecursiveAttribute.php, src/Tempest/Reflection/tests/Fixtures/RecursiveAttribute.php, src/Tempest/Validation/tests/Rules/IPv6Test.php, tests/Integration/ORM/IsDatabaseModelTest.php, tests/Integration/ORM/Migrations/CreateCarbonModelTable.php, tests/Integration/ORM/Models/CarbonModel.php
=> fix(database): loading database relations or other objects

src/Tempest/View/src/Renderers/TempestViewRenderer.php, tests/Fixtures/Views/view-component-with-use-import.view.php
=> fix(view): use bug when compiling view

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/workflows/close-stale.yml, README.md, eslint.config.mjs
This pull request:
- Improves the looks of the `README.md` file
- Removes the "bug" and "feature request" labels from issue templates, as well as the title prefixes, in favor of issue types (see https://github.blog/changelog/2025-01-13-evolving-github-issues-public-preview/ and https://github.com/orgs/community/discussions/139933)
I also updated the colors of the module labels to a single color, because it was a bit noisy. Now, we can scan other labels more easily.
I also think we should introduce "priority" labels, eg. `critical`, `high`, `medium` and `low`.
=> chore: improve readme and update labels

composer.json, src/Tempest/Console/src/Components/Interactive/TaskComponent.php, src/Tempest/View/src/Renderers/BladeInitializer.php, src/Tempest/View/src/Renderers/BladeViewRenderer.php, tests/Integration/Console/Fixtures/InteractiveCommand.php
=> chore(view): use tempest/blade

src/Tempest/Core/src/Kernel.php, src/Tempest/View/src/Elements/ElementFactory.php, src/Tempest/View/src/Elements/RawElement.php, src/Tempest/View/src/Renderers/TempestViewCompiler.php, tests/Integration/View/TempestViewRendererTest.php
=> fix(view): render doctype and html tags properly

src/Tempest/View/src/Renderers/TempestViewCompiler.php, tests/Fixtures/Views/overview.view.php, tests/Fixtures/Views/withViewModel.php, tests/Integration/View/TempestViewRendererDataPassingTest.php, tests/Integration/View/TempestViewRendererTest.php, tests/Integration/View/ViewComponentTest.php, tests/Integration/View/ViewTest.php
=> fix(view): fix for compiling HTML documents that contain PHP

tests/Integration/Mapper/Fixtures/Name.php, tests/Integration/Mapper/Fixtures/Person.php, tests/Integration/Mapper/MapperTest.php
=> chore(mapper): add test for nested value objects

src/Tempest/Debug/src/DOMDebug.php, src/Tempest/View/src/Elements/ViewComponentElement.php, tests/Integration/View/ViewComponentTest.php
=> fix(view): comment out empty slots

src/Tempest/Mapper/src/Casters/ArrayCaster.php, src/Tempest/Mapper/src/Exceptions/CannotSerializeValue.php, src/Tempest/Mapper/src/Mappers/JsonToArrayMapper.php, src/Tempest/Mapper/src/Mappers/JsonToObjectMapper.php, src/Tempest/Mapper/src/Mappers/ObjectToArrayMapper.php, src/Tempest/Mapper/src/Mappers/ObjectToJsonMapper.php, src/Tempest/Mapper/src/ObjectFactory.php, tests/Integration/Mapper/Fixtures/EnumToCast.php, tests/Integration/Mapper/Fixtures/Name.php, tests/Integration/Mapper/Fixtures/ObjectThatShouldUseCasters.php, tests/Integration/Mapper/Fixtures/Person.php, tests/Integration/Mapper/MapperTest.php, tests/Integration/Mapper/Mappers/ArrayToJsonMapperTestCase.php, tests/Integration/Mapper/Mappers/JsonToArrayMapperTestCase.php, tests/Integration/Mapper/Mappers/ObjectToArrayMapperTestCase.php, tests/Integration/Mapper/Mappers/ObjectToJsonMapperTestCase.php
=> feat(mapper): `ObjectToArrayMapper` use `Caster::serialize` to serialize the property value

src/Tempest/View/src/Elements/ElementFactory.php, src/Tempest/View/src/Elements/ViewComponentElement.php, tests/Integration/View/ViewComponentTest.php
=> feat(view): remove empty slots in production

src/Tempest/Router/src/Mappers/PsrRequestToRequestMapper.php, tests/Fixtures/Modules/Posts/PostRequest.php, tests/Integration/Mapper/PsrRequestToRequestMapperTest.php
=> feat(http): empty request values are converted to null

src/Tempest/Vite/src/Installer/ViteInstaller.php
closes https://github.com/tempestphp/tempest-framework/issues/973
I removed the link to the docs, we don't have them yet (but soon!)
=> chore(vite): update installer instructions

src/Tempest/Router/src/Mappers/PsrRequestToRequestMapper.php, src/Tempest/Router/src/Mappers/RequestToObjectMapper.php, tests/Fixtures/Modules/Posts/PostRequest.php, tests/Integration/Mapper/MapperTest.php, tests/Integration/Mapper/PsrRequestToRequestMapperTest.php, tests/Integration/Route/Fixtures/RequestObjectA.php, tests/Integration/Route/Fixtures/RequestObjectB.php, tests/Integration/Route/RequestToObjectMapperTest.php
Closes #991
Reverts #976
Closes #990
=> refactor(mapper): mapper improvements

src/Tempest/View/src/Elements/ViewComponentElement.php, tests/Integration/View/ViewComponentTest.php
=> feat(view): fallthrough attributes

src/Tempest/Support/src/Arr/ManipulatesArray.php, src/Tempest/Support/src/Arr/functions.php
=> refactor(support): rename `map` to `map_array`

src/Tempest/Console/src/Commands/MakeCommandCommand.php, src/Tempest/Console/src/Stubs/CommandStub.php, src/Tempest/Generation/src/StubFileGenerator.php, tests/Integration/Console/Commands/MakeCommandCommandTest.php
This PR checks a TODO on #759 
It adds a command to ... make commands !
The circle is complete 😎
=> feat(console): add `make:command` command

src/Tempest/Database/src/Builder/ModelInspector.php, src/Tempest/Database/src/IsDatabaseModel.php, src/Tempest/Router/src/GenericRouter.php, src/Tempest/Validation/src/Exceptions/ValidationException.php, src/Tempest/Validation/src/Validator.php, tests/Integration/ORM/IsDatabaseModelTest.php, tests/Integration/ORM/Models/ModelWithValidation.php
=> feat(database): model validation before update, create, and save

src/Tempest/Console/src/Stubs/CommandStub.php, src/Tempest/Console/src/Stubs/GeneratorCommandStub.php
Closes #1134
Also see #1137 as followup
=> fix(console): do not discover stub files

src/Tempest/Console/src/Components/Concerns/OpensInEditor.php, src/Tempest/Console/src/Components/Interactive/SingleChoiceComponent.php, src/Tempest/Console/src/Key.php, tests/Integration/Console/Components/SingleChoiceComponentTest.php, tests/Integration/Console/Fixtures/InteractiveCommand.php
=> fix(console): select default option in ask component

src/Tempest/Console/src/Components/Renderers/TextInputRenderer.php
The code is not very pretty but it's fine for now.
Closes #1140
=> fix(console): properly place cursor in multiline input

src/Tempest/Router/src/Commands/RoutesCommand.php
This pull request improves the formatting of `routes:list`. I'll fix the line length issue in another PR.
**After**
**Before**
=> refactor(console): improve `routes:list` formatting

src/Tempest/View/src/Components/Icon.php, src/Tempest/View/src/Components/x-icon.view.php, tests/Integration/View/IconComponentTest.php
Closes https://github.com/tempestphp/tempest-framework/issues/1146
Closes https://github.com/tempestphp/tempest-framework/issues/1144
Closes #1163
=> fix(view): switch to runtime icon view component

src/Tempest/View/src/Components/DynamicViewComponent.php, src/Tempest/View/src/Elements/ElementFactory.php, src/Tempest/View/src/Elements/ViewComponentElement.php, src/Tempest/View/src/Parser/TempestViewCompiler.php, tests/Integration/View/ViewComponentTest.php
=> feat(view): dynamic view components

src/Tempest/Container/src/GenericContainer.php, src/Tempest/Container/src/Proxy.php, src/Tempest/Container/tests/Fixtures/ClassWithLazySlowDependency.php, src/Tempest/Container/tests/Fixtures/ClassWithLazySlowPropertyDependency.php
=> refactor(container): rename #[Lazy] to #[Proxy]

packages/view/src/Exceptions/InvalidClosingTag.php, packages/view/src/Parser/Token.php, packages/view/tests/Fixtures/html/4.html, packages/view/tests/TempestViewParserTest.php, tests/Integration/View/ViewComponentDiscoveryTest.php
This should be further improved with #1194 in the long run
=> feat(view): prevent invalid closing tags

composer.json, packages/support/src/Arr/ManipulatesArray.php, packages/support/src/Comparison/Order.php, packages/support/src/Conditions/HasConditions.php, packages/support/src/Filesystem/Exceptions/NotDirectoryException.php, packages/support/src/Filesystem/Exceptions/NotFileException.php, packages/support/src/Filesystem/Exceptions/NotFoundException.php, packages/support/src/Filesystem/Exceptions/NotSymbolicLinkException.php, packages/support/src/Html/HtmlString.php, packages/support/src/IsEnumHelper.php, packages/support/src/Path/Path.php, packages/support/src/Str/ImmutableString.php, packages/support/src/Str/ManipulatesString.php, packages/support/src/Str/MutableString.php, packages/support/tests/Conditions/HasConditionsTest.php, tests/Integration/Support/GeneratesArguments.php
=> refactor(support): change static return type to self for better autocompletion support

packages/router/src/Static/StaticGenerateCommand.php
Fixes https://github.com/tempestphp/tempest-framework/issues/1209
=> fix(router): check internal dead links without the domain

packages/view/src/Elements/PhpDataElement.php, tests/Integration/View/ViewComponentTest.php
=> fix(view): properly unset local view component variables

packages/view/src/Attributes/AttributeFactory.php, packages/view/src/Attributes/EscapedExpressionAttribute.php, tests/Integration/View/TempestViewRendererTest.php, tests/Integration/View/ViewComponentTest.php
=> feat(view): support escaped expression attributes

packages/cache/src/CacheConfig.php
=> fix(core): allow discovery:generate to run even when full caching is enabled

packages/console/src/Console.php
This pull request adds inline documentation to console methods. This improves the DX. :)
=> feat(console): add inline documentation to console methods

packages/database/src/Builder/ModelInspector.php, packages/database/src/Builder/QueryBuilders/BuildsQuery.php, packages/database/src/Builder/QueryBuilders/CountQueryBuilder.php, packages/database/src/Builder/QueryBuilders/DeleteQueryBuilder.php, packages/database/src/Builder/QueryBuilders/InsertQueryBuilder.php, packages/database/src/Builder/QueryBuilders/SelectQueryBuilder.php, packages/database/src/Builder/QueryBuilders/UpdateQueryBuilder.php, packages/database/src/Exceptions/CannotInsertHasOneRelation.php, packages/database/src/Exceptions/CannotUpdateHasOneRelation.php, packages/database/src/Query.php, tests/Fixtures/Migrations/CreateChapterTable.php, tests/Fixtures/Modules/Books/Models/Book.php, tests/Fixtures/Modules/Books/Models/Isbn.php, tests/Integration/Database/Builder/InsertQueryBuilderTest.php, tests/Integration/Database/Builder/UpdateQueryBuilderTest.php
=> feat(database): add insert()->then() and prevent invalid relations from being attached

packages/database/src/Builder/QueryBuilders/SelectQueryBuilder.php, tests/Integration/Database/Builder/DeleteQueryBuilderTest.php, tests/Integration/Database/Builder/InsertQueryBuilderTest.php, tests/Integration/Database/Builder/SelectQueryBuilderTest.php, tests/Integration/Database/Builder/UpdateQueryBuilderTest.php
=> fix(database): prevent non-object model queries from trying to use the model class

packages/vite-plugin-tempest/src/config.test.ts, packages/vite-plugin-tempest/src/config.ts
Closes https://github.com/tempestphp/tempest-framework/issues/1254
=> feat(vite-plugin-tempest): allow overriding configuration using `TEMPEST_PLUGIN_CONFIGURATION_OVERRIDE`

packages/vite/src/Installer/ViteInstaller.php
=> fix(vite): ignore missing `.gitignore` during installation

packages/database/src/DatabaseInsightsProvider.php, packages/database/tests/DatabaseInsightsProviderTest.php
=> feat(database): display sqlite path in `about` command

packages/view/src/Elements/TextElement.php, tests/Integration/View/TempestViewRendererTest.php
=> feat(view): add view comments

composer.json, packages/storage/src/AdapterWasMissing.php, packages/storage/src/Config/AzureStorageConfig.php
the original flysystem package was marked as abandoned 5 months ago
https://github.com/thephpleague/flysystem-azure-blob-storage/commit/731d07713f3541f3f204817117f27d4c7f175c5a
=> refactor(filesystem): switch to the recommended azure blog storage lib

packages/database/src/Config/DatabaseDialect.php, packages/database/src/Exceptions/QueryWasInvalid.php, packages/database/src/GenericDatabase.php, packages/database/src/Migrations/MigrationManager.php, tests/Integration/Database/GenericDatabaseTest.php, tests/Integration/Database/MultiDatabaseTest.php
=> fix(database): throw `QueryWasInvalid` on database fetch failure

packages/router/src/Bindable.php
=> fix(router): change the `Bindable::resolve` return type from `static` to `self`

packages/command-bus/composer.json, tests/Integration/Console/Components/TaskComponentTest.php
=> fix(commandbus): require console as a dependency

packages/auth/src/Allow.php, packages/auth/src/AuthorizerMiddleware.php, tests/Fixtures/Controllers/AdminController.php
=> feat(auth): add class-level permission support

packages/router/src/Commands/MakeControllerCommand.php, packages/router/src/Stubs/ControllerStub.php, tests/Integration/Http/MakeControllerCommandTest.php
=> fix(router): do not discover controller stub

packages/view/src/Elements/ViewComponentElement.php, tests/Integration/Http/GenericResponseSenderTest.php, tests/Integration/View/ViewComponentTest.php
=> fix(view): pass scoped variables down view components

packages/core/src/LogExceptionProcessor.php, packages/http/src/HttpRequestFailed.php, packages/icon/src/Icon.php, packages/router/src/HandleRouteExceptionMiddleware.php, tests/Integration/Http/HttpExceptionHandlerTest.php
=> feat(http): improve context for failed http requests

src/Tempest/Framework/Testing/Http/TestResponseHelper.php, tests/Integration/Route/RequestToObjectMapperTest.php
=> fix(http): fix assertStatus mixing up expected and actual results

packages/container/src/Exceptions/TaggedDependencyCouldNotBeResolved.php, packages/container/src/Tag.php, packages/container/tests/ContainerTest.php, packages/container/tests/Fixtures/AutowireWithEnumTags.php, tests/Integration/Core/DiscoveryCacheTest.php
=> fix(container): allow enums in the #[Tag] attribute

docs/1-essentials/07-testing.md, src/Tempest/Framework/Testing/IntegrationTest.php, tests/Integration/FrameworkIntegrationTestCase.php
=> feat(core): improve base testing class

packages/database/src/Mappers/SelectModelMapper.php, tests/Integration/Database/Builder/IsDatabaseModelTest.php
=> fix(database): saving nullable `BelongsTo` relations

packages/http/src/Session/Installer/DatabaseSessionInstaller.php, tests/Integration/Http/DatabaseSessionInstallerTest.php
This fixes an oversight in the previous PR, and adds a test for it
=> fix(http): publish migration during database session driver installation
