src/Validation/Rules/Url.php, tests/Validation/Rules/UrlTest.php
This pull request just does a little housekeeping on the URL validation rule. Copyright information is added and support for protocols beyond http/https is ensured.
The desired protocols can be restricted by specifying the `$protocols` parameter in the constructor.
=> Cleanup URL validation rule

src/Validation/Rules/Email.php, src/Validation/Rules/PhoneNumber.php, tests/Validation/Rules/EmailTest.php, tests/Validation/Rules/PhoneNumberTest.php
This pull request removes punctuation from the `Email` and `PhoneNumber` rules to be consistent with the rest of the rules.
=> Make the punctuation style of rule messages consistent

src/Validation/Rules/Time.php, tests/Validation/Rules/TimeTest.php
This rule uses regex to validate time in standard format (hh:mm xm) or military (24-hour) format (hh:mm). It covers the rule mentioned in #3.
=> Adds time rule

src/Validation/Rules/DoesNotEndWith.php, src/Validation/Rules/DoesNotStartWith.php, src/Validation/Rules/Lowercase.php, src/Validation/Rules/Uppercase.php, tests/Validation/Rules/DoesNotEndWithTest.php, tests/Validation/Rules/DoesNotStartWithTest.php, tests/Validation/Rules/LowercaseTest.php, tests/Validation/Rules/UppercaseTest.php
Not sure if should have just used the StartsWith and EndsWith rules directly and negate their return.
Something like this: 
```php
$startsWithRule = new StartsWith($needle);
return !$startsWithRule->isValid($value);
```
=> feat: add not starts with and not ends with validation rules

src/Validation/Rules/JSON.php, tests/Validation/Rules/JSONTest.php
I know is not in the list, but I think it might be useful to have it. 
Also it might look ugly, but wanted to use the new function json_validate, maybe instead of adding this polyfill I could just move the body of the function inside the isValid method.
=> feat: add json validation rule

src/Validation/Rules/Password.php, tests/Validation/Rules/PasswordTest.php
Added some basic password validation (addresses #3)
Have selected most rules to be disabled by default. NIST guidelines don't recommend any sort of password enforcement. Instead they recommend using a list of compromised passwords to compare against (which we are handling separately).
I'm not sure if we want to have different messages for different issues - but then we may want message() to allow returning an array of errors. Seems like it's something a little out of scope for this one though.
Source: https://pages.nist.gov/800-63-FAQ/#q-b06
=> Validate password

.env.example, src/Application/Exceptions/KernelException.php, src/Application/Kernel.php
Replace namespace source with root `composer.json` `"autoload"` data and `vendor/composer/installed.json` `"packages"` data
Root `composer.json` includes `"autoload-dev"` conditionally on `ENVIRONMENT` value
=> #117 Use installed.json for package discovery

src/Testing/Http/TestResponse.php, src/Testing/Http/TestResponseSender.php, src/Testing/Http/TestResponseSenderInitializer.php, src/Testing/Http/TestsHttpRequests.php, src/Testing/TestCase.php, tests/TestingTest.php
@brendt Not sure if you have any input here. I am somewhat following Laravel's syntax for testing for now (there may be some things we change along the way).
A few things that I am running into:
1. We do not currently have a way to set priority for an initializer, right? What's the best way to override a default implementation?
2. Due to the application self-processing the request, we basically cut it out entirely in the test helper. Not sure if we are just fine with that or if you have other thoughts here.
=> Add test helpers

src/Http/Responses/CreatedResponse.php, src/Tempest.php, tests/Http/Responses/CreatedResponseTest.php
Hi!
Regarding [Issue #39](https://github.com/tempestphp/tempest-framework/issues/39) this PR adds:
- Adds preconfigured CreatedResponse and it's test.
Let  me know if something must to be changed.
Thanks!
=> Response objects

public/index.php, src/Application/Kernel.php, src/Bootstraps/Bootstrap.php, src/Bootstraps/BootstrapException.php, src/Bootstraps/ConfigBootstrap.php, src/Bootstraps/DiscoveryBootstrap.php, src/Bootstraps/DiscoveryLocationBootstrap.php, src/Tempest.php
* Remove `Tempest::__construct()` `$appConfig` parameter - available from Container object
* Add `Kernel::__construct()` `$bootstraps` promoted property
* Rename `Kernel::initContainer()`
* Add Bootstrap classes for Discovery and Config
* Loop `$bootstraps` to register them in the Container as singletons
* Execute Bootstraps `boot()` in `Kernel::init()`
* Set Bootstraps as third Kernel constructor argument
* Fixed some accessors to AppConfig from the `$kernel` object
=> Refactor Kernel to extract Bootstraps

README.md
Getting started path has changed, it sends to a 404 at this time, this corrects and links to the new path.
=> Update README.md for getting started

tests/Architecture/ArchitectureTest.php
As per https://github.com/tempestphp/tempest-framework/issues/116#issuecomment-1970395938
* Added a test to make sure there are no abstract classes.
* From bullet point 2 and 3 we can extract a test to make sure that all classes are final.
* Added a test to make sure that classes that implement anything are readonly.
I've added these tests exactly as they were described in Brent's comment. There are 88 errors currently that would need to be addressed to satisfy those rules. I do believe that there will be exceptions to these rules so I'm not sure how feasible it will be to implement them.
=> Added additional architecture tests

src/Tempest/Database/Drivers/MySqlDriver.php, tests/Unit/Database/DatabaseDriverTest.php
fixes #292
As outlined in the issue the format of the DSN that the MySQL creates did not have the right format.
This PR fixes the format and adds a very simple test to check the DSN both for MySQL and Sqlite. With the possibility to add PostgreSQL.
=> [bug] fix MySQL driver DSN format

src/Tempest/Database/Drivers/PostgreSqlDriver.php, tests/Unit/Database/DatabaseDriverTest.php
resolves #295
This PR adds a driver for using the PostgreSQL database. Pretty straightforward, mirrored after the MySQL driver.
I don't have PostgreSql locally, so I've not been able to test this.
=> add a driver for PostgreSql

.gitignore, .php-cs-fixer.dist.php, phpstan.neon.dist, phpunit.xml, src/Tempest/CommandBus/CommandBusDiscovery.php, src/Tempest/Console/Discovery/ConsoleCommandDiscovery.php, src/Tempest/Console/Discovery/ScheduleDiscovery.php, src/Tempest/Console/Discovery/ScheduleDisovery.php, src/Tempest/Console/Scheduler/GenericScheduler.php, src/Tempest/Container/InitializerDiscovery.php, src/Tempest/Database/MigrationDiscovery.php, src/Tempest/Discovery/DiscoveryDiscovery.php, src/Tempest/EventBus/EventBusDiscovery.php, src/Tempest/Http/RouteDiscovery.php, src/Tempest/Mapper/MapperDiscovery.php, src/Tempest/View/ViewComponentDiscovery.php, tests/Integration/View/BladeViewRendererTest.php, tests/Unit/KernelTest.php
This might just be a personal preference, but this PR moves all the cache files to a single directory.
Instead of having them scattered throughout 
**Additional**
- enabled the cache for PHPStan
- enable parallel fixing for CS fixer
**Note**
Enabling cache on Github Actions is also possible :)
=> move cache files to a single directory

src/Tempest/CommandBus/CommandBusDiscovery.php, src/Tempest/Console/Discovery/ConsoleCommandDiscovery.php, src/Tempest/Console/Discovery/ScheduleDiscovery.php, src/Tempest/Console/Scheduler/GenericScheduler.php, src/Tempest/Console/Testing/ConsoleTester.php, src/Tempest/Container/InitializerDiscovery.php, src/Tempest/Discovery/DiscoveryDiscovery.php, src/Tempest/EventBus/EventBusDiscovery.php, src/Tempest/Framework/Bootstraps/DiscoveryBootstrap.php, src/Tempest/Http/GenericRouter.php, src/Tempest/Http/Session/Managers/FileSessionManager.php, src/Tempest/Mapper/MapperDiscovery.php, src/Tempest/Support/Reflection/TypeReflector.php, src/Tempest/View/ViewComponentDiscovery.php
This PR allows us to be more strict with the `unserialize(..)` behaviour.
If a different payload is given than the one we allow, then the application will throw an exception.
This was already done in #306 for the Migration cache, and I think that it's good to be security focused when dealing with outside input. Wether human based, or computational based.
=> [security] allow only known classes to unserialize

.github/workflows/quality-assurance.yml, .github/workflows/quality-control.yml, src/Tempest/Console/Testing/ConsoleTester.php, src/Tempest/Support/PathHelper.php, tests/Integration/Console/Components/MultipleChoiceComponentTest.php, tests/Integration/Console/Components/Static/StaticProgressBarComponentTest.php, tests/Integration/Console/Components/Static/StaticSearchComponentTest.php, tests/Integration/View/TempestViewRendererTest.php, tests/Integration/View/ViewComponentTest.php, tests/Integration/View/ViewTest.php, tests/Unit/Container/ContainerTest.php, tests/Unit/Container/Exceptions/CannotAutowireExceptionTest.php, tests/Unit/Container/Exceptions/CircularDependencyExceptionTest.php, tests/bootstrap.php
I mainly use wsl2 to work on projects, but, I saw that there is PR to add a windows runner. The only tests that failed for me on windows  where related to different line endings between the expected string and the result (lf vs clrf), and most of the console related tests, but those where related to how the tests/bootstrap.php file was trying to run the `tempest discovery:clear` command, for windows it needs to be run with php explicitly.
If this changes make no sense at all please feel free to close the pr, thanks.
=> refactor: fix tests on windows

src/Tempest/View/Renderers/TempestViewRenderer.php
When the extract part is in an isolated method, variables from the `resolveContent` method can be reused in the view file.
Conflicts with variables like `$view` or `$path` e.g. are prevented. Only `$_path` and `$_data` are reserved as a minimum.
=> Isolate extract method

CHANGELOG.md, composer.json, src/Tempest/Support/composer.json, src/Tempest/Support/src/LanguageHelper.php, src/Tempest/Support/src/Pluralizer/InflectorPluralizer.php, src/Tempest/Support/src/Pluralizer/Pluralizer.php, src/Tempest/Support/src/Pluralizer/PluralizerInitializer.php, src/Tempest/Support/tests/LanguageHelperTest.php, src/Tempest/Support/tests/Pluralizer/InflectorPluralizerTest.php, tests/Integration/Support/LanguageHelperTest.php
This pull request adds support for pluralizing (or singularizing) nouns through `doctrine/inflector`. The implementation is a simplified and cleaner version of Laravel's.
This can be used as a helper in application code through `LanguageHelpers::pluralize()`, but is also intended to be used in the framework itself, such as in database table names, exception and log messages, validation, etc.
Note: I didn't know if I should make a new package or put it in the support one, so I kept things simple and added it to `Support`. I'm assuming `Support` will grow over time and it's not a bad place to have it, but at the same time, `Clock` is a separate package, so I don't know. Happy to update the PR.
Related: https://discord.com/channels/1236153076688359495/1236153079603269766/1268515847073173606
=> feat(support): add `Pluralizer` implementation

.github/CONTRIBUTING.md
Follow-up of https://github.com/tempestphp/tempest-framework/pull/425
This pull request updates the `CONTRIBUTING.md` file to specify new commit and pull request conventions.
I've tried to be as clear as possible without being too restrictive for contributors—let me know if I should change anything
=> chore: specify commit conventions in `CONTRIBUTING.md`

src/Tempest/View/src/Renderers/TempestViewRenderer.php, tests/Integration/View/ViewComponentTest.php, tests/Integration/View/ViewTest.php
On the live docs, I noticed there's a space between inline elements and text: 
This happens because the Tempest view renderer separates elements with `PHP_EOL`, so the generated HTML has a new line. In this case, the generated HTML is the following:
```html
<p><strong>Tempest is a PHP framework that gets out of your way</strong>
. Its design philosophy is that developers should write as little framework-related code as possible, so that they can 
<strong>focus on application code</strong>
instead.</p>
```
This pull request changes this behavior by separating generic elements with an empty string, resulting in the following HTML:
```html
<p><strong>Tempest is a PHP framework that gets out of your way</strong>. Its design philosophy is that developers should write as little …
```
=> fix(view/tempest-renderer): join generic elements with an empty string

.commitlintrc.json, .gitattributes, .github/workflows/lint-pr-title.yml
This pull request adds a GitHub Action that lints pull request titles, so we don't forget to rename them before merging.
This is done through the [commitlint](https://commitlint.js.org/) project, which is quite [configurable](https://commitlint.js.org/reference/rules.html), so we may update rules as you see fit
=> ci: lint pull request title

src/Tempest/Console/src/Components/Interactive/ConfirmComponent.php, src/Tempest/Console/src/Components/Interactive/MultipleChoiceComponent.php, src/Tempest/Console/src/Components/Interactive/PasswordComponent.php, src/Tempest/Console/src/Components/Interactive/ProgressBarComponent.php, src/Tempest/Console/src/Components/Interactive/SearchComponent.php, src/Tempest/Console/src/Components/Interactive/SingleChoiceComponent.php, src/Tempest/Console/src/Components/Interactive/TextBoxComponent.php, src/Tempest/Console/src/Components/InteractiveComponentRenderer.php, src/Tempest/Console/src/Components/Static/StaticConfirmComponent.php, src/Tempest/Console/src/Components/Static/StaticMultipleChoiceComponent.php, src/Tempest/Console/src/Components/Static/StaticProgressBarComponent.php, src/Tempest/Console/src/Components/Static/StaticSearchComponent.php, src/Tempest/Console/src/Components/Static/StaticSingleChoiceComponent.php, src/Tempest/Console/src/Components/Static/StaticTextBoxComponent.php, src/Tempest/Console/src/Console.php, src/Tempest/Console/src/Exceptions/UnsupportedComponent.php, src/Tempest/Console/src/GenericConsole.php, src/Tempest/Console/src/HasStaticComponent.php, src/Tempest/Console/src/InteractiveConsoleComponent.php, src/Tempest/Console/src/StaticConsoleComponent.php, src/Tempest/Console/src/Terminal/Terminal.php
I noticed during a demo that the naming of these interfaces wasn't all that intuitive. Even though these are longer, I think it makes more sense (especially now that we also have a `ViewComponent` interface, I think it's best to have a clear distinction between them
=> fix: rename console component interfaces

src/Tempest/Container/src/AutoDiscovery.php, src/Tempest/Container/src/Autowire.php, src/Tempest/Container/src/AutowireDiscovery.php, src/Tempest/Container/src/GenericContainer.php
First of all, it is exciting to play with this new framework! I like a lot of it already, but I hit one snag when building some services. I usually have an interface for them (for example to make mocking easier). But with Tempest it looks like this would require a initializer class. And I am too lazy to make those for all my services 😜 
A while ago I made an Autowire implementation for Laravel ([link](https://github.com/Jeroen-G/autowire/)) so I thought I would start porting that a little bit to Tempest. So this first PR adds the Autowire attribute which allows autodiscovery of classes (or maybe auto initialization is a name better fitting to Tempest).
Let me know what you think!
GreetingController:
```php
final readonly class GreetingController
{
public function __construct(public …
```
=> feat: add autowire/autodiscovery/auto-initialization of interfaces to classes

src/Tempest/Core/src/DoNotDiscover.php, src/Tempest/Core/src/HideFromDiscovery.php, src/Tempest/Core/src/Kernel/LoadDiscoveryClasses.php, tests/Fixtures/Discovery/HiddenMigration.php, tests/Integration/Core/LoadDiscoveryClassesTest.php
This pull request adds the ability to hide classes from all discovery implementations by adding a `HideFromDiscovery` attribute (**edit**: updated to `DoNotDiscover`).
Happy to change the attribute name to anything else:
- `SkipDiscovery`
- `IgnoreFromDiscovery`
- `WithoutDiscovery`
- `\Tempest\Core\Discovery\Ignore`
- `\Tempest\Core\Discovery\Skip`
Closes #338
Related to #509
=> feat(discovery): add ability to hide classes from discovery

src/Tempest/Core/src/DoNotDiscover.php, src/Tempest/Core/src/Kernel/LoadDiscoveryClasses.php, tests/Fixtures/Discovery/HiddenMigratableMigration.php, tests/Integration/Core/LoadDiscoveryClassesTest.php
This pull request is a follow-up of #512—it adds the ability for classes that should not be discovered by Discovery to still be seen by the specified Discovery classes.
For instance, publishable classes that generally should not be discovered may allow the `tempest publish` command to show them as publishable classes.
Related to #513
=> feat(discovery): allow exceptions on `DoNotDiscover` classes

phpstan.neon.dist, src/Tempest/Core/src/Composer.php, src/Tempest/Core/src/ComposerNamespace.php, src/Tempest/Core/src/Kernel.php, src/Tempest/Core/src/Kernel/LoadDiscoveryLocations.php, tests/Fixtures/Core/Composer/.gitignore, tests/Integration/Core/ComposerTest.php
This pull request introduces a `Composer` util class in `tempest/core`, that's useful for reusing composer-related code in other parts of the framework.
I have refactored a little part of `LoadDiscoveryLocations` with it, and will be using it as well in #513.
Later on, we can move more composer-related code into this class, but I preferred not to move to many things around in this specific pull request, for simplicity.
=> feat(core): add `Composer` util

.commitlintrc.json
This pull request decreases the strictness of the linting or pull request titles. The following commit name is now allowed:
```
feat(core): add `Composer` util 
```
It was previously not allowed due to the uppercase `C`, which should not be forbidden.
=> ci(lint-pr-title): fix subject case rule

src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/tests/StringHelperTest.php
While working on other parts of Tempest, I came across the need to use methods added in this pull request.
- Multiple `replace` methods
- `append` and `prepend` for chaining
I also slightly updated the definitions of `after` and `before` to support searching with arrays instead of just strings.
I added a `dd` method, as it was tedious to keep wrapping the whole chain when working on it—however, I could not use the `never` return type because the underlying `dd` function does not use it and thus triggers phpstan.
I also bypassed phpstan's warning on the usage of `dd` by using the underlying `ld` function instead of adding an exception for this warning.
=> feat(string-helper): add replacement and concatenation methods

src/Tempest/Console/src/Components/Interactive/TextBoxComponent.php, src/Tempest/Console/src/GenericConsole.php
This pull request adds support for the `default` parameter of `Console#ask`, which wasn't passed down nor taken into account in `TextBoxComponent`.
Note: my approach was the easiest I could think of—reusing the existing methods instead of adding a new cursor manipulation, at the cost of introducing a loop, which I believe is fast enough to not care about it.
=> fix(console): support `default` parameter on textbox component

src/Tempest/Mapper/src/Mappers/ObjectToArrayMapper.php, tests/Integration/Mapper/Fixtures/ObjectWithJsonSerialize.php, tests/Integration/Mapper/Mappers/ObjectToArrayMapperTestCase.php
I wrote an object that I wanted to be mapped to array differently then just property -> value. PHP supports this with the JsonSerialize interface. So I wrote a simple check (with test) for that!
For the example, I think the test speaks for itself.
=> feat: allow object to define how they are mapped to array

src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/tests/StringHelperTest.php
I think I did a bad job on the first PR about this helper, this aims to improve the method a bit, and I simplify the no match result.
=> refactor: improve matchAll string helper

src/Tempest/Http/src/Commands/ServeCommand.php
Tempest serves without specifying a port:
```bash
./tempest serve --host=localhost 
```
With a specific port:
```bash
./tempest serve --host=localhost --port=8082 
```
=> fix: add optional port argument to serve command(#537)

src/Tempest/Container/src/Container.php, src/Tempest/Container/src/Exceptions/InvalidInitializerException.php, src/Tempest/Container/src/GenericContainer.php, src/Tempest/Container/src/Initializer.php, src/Tempest/Container/tests/ContainerTest.php, src/Tempest/Container/tests/Fixtures/BuiltinDependencyArrayInitializer.php, src/Tempest/Container/tests/Fixtures/BuiltinDependencyBoolInitializer.php, src/Tempest/Container/tests/Fixtures/BuiltinDependencyStringInitializer.php, src/Tempest/Container/tests/Fixtures/DependencyWithBuiltinDependencies.php
Hi again,
In #522  we briefly discussed how it wasn't yet possible to initialize native types (like arrays). With these changes you should be able to do so. With it you can inject arrays like any other class without the help of your ArrayHelper. In my opinion, not having to use the ArrayHelper is more in line with the project goals of "getting out of the way" where you can use builtin types without the wrappers (and with if you prefer of course). 
I hope you guys like it as much as I do.
With this you can inject an array , string, bool and more. The "most common" usage would be to inject groups of dependencies more easily. But you could even inject config values with it. 
```php
final class InspiratorCombinatorInitializer implements Initializer
{
#[Singleton(tag: 'inspirators')]
public …
```
=> feat: add initializer for builtin types

src/Tempest/Container/src/Container.php, src/Tempest/Container/src/Exceptions/InvalidCallableException.php, src/Tempest/Container/src/GenericContainer.php, src/Tempest/Container/src/functions.php, src/Tempest/Container/tests/ContainerTest.php, src/Tempest/Container/tests/Fixtures/InvokableClass.php, src/Tempest/Container/tests/Fixtures/InvokableClassWithParameters.php, src/Tempest/Reflection/src/FunctionReflector.php
This pull request adds the ability to invoke closures from the container. Previously, the container only had the ability to invoke class methods.
```php
$this->container->invoke(function (Kernel $kernel) {});
$this->container->invoke(function (string $foo) {}, foo: 'bar');
$this->container->invoke(InvokableClass::class);
$this->container->invoke([ServiceClass::class, 'handle']);
\Tempest\invoke(function (Service $service) {});
```
=> feat(container): add ability to invoke arbitrary closures

src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/tests/ArrayHelperTest.php, src/Tempest/Support/tests/StringHelperTest.php
This pull request adds some improvements to `ArrayHelper` and `StringHelper`:
- Added a `explode` constructor for better chaining (I wanted to use that in #513)
- Added support for no callback on the `filter` method—by default, it filters out `false` and `null` values (strictly)
- Added a `dd` method to help with debugging
- Added `Stringable` support where it made sense
- Added `toString` for better chaining (`__toString` is ugly, `(string)` feels bad)
- Renamed `ld` to `dd` (I learned that we could ignore a line with phpstan, and `dd` is more intuitive to reach for than `ld`)
=> feat(support): improve helpers

src/Tempest/Log/src/Channels/WeeklyLogChannel.php, src/Tempest/Log/src/FileHandlers/RotatingFileHandler.php, src/Tempest/Log/tests/GenericLoggerTest.php
Added weekly log rotation.
This fix creates a `RotatingFileHandler` that extends the `Mono/RotatingFileHandler` and overwrites only the methods required to make this work. Might be considered hacky by some.
=> fix(#275): implement weekly log rotation

bin/release
This pull request adds a `./bin/release` script that interactively creates a tag and pushes it to Git.
The script:
- Checks if the repository is in a clean state
- Check if the current origin and branch is `origin/main` (this could be changed or made dynamic)
- Checks if the user has write access by calling `git push`
- Suggests new versions based on the current version
- Creates and pushes the tag for the chosen version
This will trigger the "Changelog and release" action which will write to `CHANGELOG.md` and create a GitHub release.
> [!WARNING]
> The current version scheme, `1.0-alpha2`, is not semver-compliant. The pre-release identifiers should be separated by dots, and the patch version should be included. It should be `1.0.0-alpha.2`.
>
> However, consistency is better, so I …
=> build: add release script

src/Tempest/Database/src/QueryStatements/BooleanStatement.php, src/Tempest/Database/src/QueryStatements/CreateTableStatement.php, tests/Integration/Database/QueryStatements/CreateTableStatementTest.php
In this `PR` the `Boolean` data type is added to the table statements. To create a column with a boolean type:
``` bash
public function up(): QueryStatement|null
{
return CreateTableStatement::forModel(Book::class)
->primary()
->text('title')
->boolean('is_active', default: true);
}
```
=> feat: add boolean data type (#547)

public/index.php, src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/tests/ArrayHelperTest.php
As discussed in #543 This pull request add some additional methods to the array helper.
As seen in other PR/Issues the goal for this helper isn't to be a clone of laravel collections but a much simpler wrapper around native php's array functions and some other useful methods such as mapWithKeys, pluck etc..
Here's my current work progression :
If i'm doing something wrong please tell me 🙏
=> feat(support): improve array helper with additional methods

src/Tempest/Support/src/StringHelper.php
Changes `dd()` method in `str()` helper to use the Logger to be consistent with the changes made in array helper.
Also added the `dump()` one for same purposes.
Have better debugging and be tracked in logs
=> feat(support): refactor dd() method to use logger in string helper and add the dump() method

src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/tests/ArrayHelperTest.php, src/Tempest/Support/tests/StringHelperTest.php
This PR add both `implode()` and `explode()` method in string helper with consistency regarding the ones in array helper.
It also update the return type of `implode()` in array helper to `StringHelper` object for consistency
=> feat(support): add implode()/explode() methods in string helper

phpstan-baseline.neon, phpstan.neon.dist, src/Tempest/Console/src/Scheduler/NullShellExecutor.php, src/Tempest/Container/tests/Fixtures/CircularWithInitializerA.php, src/Tempest/Container/tests/Fixtures/CircularWithInitializerB.php, src/Tempest/Container/tests/Fixtures/CircularWithInitializerC.php, src/Tempest/Database/src/Builder/ModelDefinition.php, src/Tempest/Http/src/Exceptions/HttpExceptionHandler.php, src/Tempest/Http/src/Exceptions/exception.php, src/Tempest/Http/src/Route.php, src/Tempest/Http/src/Status.php, src/Tempest/HttpClient/src/Driver/Psr18Driver.php, src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/src/StringHelper.php
Related to #379
I resolved some issues related to phpstan. I moved some ignore patterns around, removed unused ignore patterns, fixed some issues.
Here is the full breakdown:
Some are ignored in the "normal" phpstan config file like others. 
- forbidden `exec` in `src/Tempest/Console/src/Terminal/Terminal.php` . Which seems as expected and other exec calls are also ignored this way
- `src/Tempest/Http/src/Exceptions/exception.php` seems to have been moved, so I changed the path for the ignore rule
Others where ignore patterns which were no longer required:
- `NullShellExecutor.php`
- `CircularWithInitializer[ABC].php`
- `ModelDefinition.php`
- I excluded the whole `tests/Integration/View/blade/cache/**.php` path instead of ignoring errors from it.
Lastly I fixed some actual  issues:
- …
=> fix(phpstan): fix phpstan issues

src/Tempest/Console/src/Components/Interactive/MultipleChoiceComponent.php, tests/Integration/Console/Components/MultipleChoiceComponentTest.php
This pull request adds support for using string keys in the options array of `MultipleChoiceComponent`. 
This is useful to have the component display something but return a different value (see https://github.com/tempestphp/tempest-framework/pull/513).
=> feat(console): support string keys in `MultipleChoiceComponent`

phpstan-baseline.neon, tests/Architecture/ArchitectureTestCase.php
I found a solution for the last "class should be final" phpstan errors.
Normally you would either have a class which is known abstract or final. So I baked that rule in the existing architecture tests.
I also removed the exception for "integrationtest" since it already is abstract.
=> fix(phpstan): fix last phpstan issues

src/Tempest/Validation/src/Validator.php
Slight refactor of my previous PR, for readability. I was going to continue the work on the validation messages, but I've decided I didn't like the API I came up with, so I'll do it later and just push this change in the meantime.
=> refactor(validation): improve readability of `validateValue`

src/Tempest/Http/src/Responses/Invalid.php, tests/Integration/Http/Responses/InvalidTest.php
This PR fixes `Call to undefined method Tempest\Http\GenericRequest::getHeader()` error that happens when the request is not an instance of `PsrRequest` when you return a `Invalid` response.
This also happens when you throw a `ValidationException` from a controller. (and according to the signature it should work 😬)
=> fix(http): fix so referer header is resolved depending on request class in invalid response

src/Tempest/EventBus/src/EventBusDiscovery.php, src/Tempest/EventBus/src/GenericEventBus.php, src/Tempest/EventBus/tests/EventBusTest.php, src/Tempest/EventBus/tests/Fixtures/EventInterface.php, src/Tempest/EventBus/tests/Fixtures/EventInterfaceHandler.php, src/Tempest/EventBus/tests/Fixtures/EventInterfaceImplementation.php, src/Tempest/EventBus/tests/Fixtures/MyEventBusMiddleware.php, src/Tempest/EventBus/tests/Fixtures/MyInterfaceEventHandler.php, src/Tempest/Reflection/src/TypeReflector.php, tests/Fixtures/Events/EventInterface.php, tests/Fixtures/Events/EventInterfaceImplementation.php, tests/Fixtures/Handlers/EventInterfaceHandler.php, tests/Integration/EventBus/EventBusTest.php
- Only apply middleware once per dispatch
- Allow event handlers to listen to interfaces
=> feat: event bus improvements

src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/src/LanguageHelper.php, src/Tempest/Support/src/PathHelper.php, src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/tests/ArrayHelperTest.php
This pull request adds inline documentation on all methods of `StringHelper`, `ArrayHelper` and `LanguageHelper`.
Not all method names are explicit enough to understand the behavior of the method, so inline documentation helps a lot.
=> feat(support): add inline documentation on helper classes

src/Tempest/Console/src/Input/ConsoleInputArgument.php, tests/Integration/Console/ConsoleArgumentBagTest.php, tests/Integration/Console/Input/ConsoleInputArgumentTest.php
This pull request adds support for converting boolean flags that start with `--no` to their non-negative version.
For instance, the flag `--no-interaction` will be parsed as `$interaction = false`. This is a common practice in JavaScript and Rust CLIs, and a practical feature, both user and developer wise, to handle boolean flags in multiple ways, whichever feels more natural.
Non-boolean flags will be handled as before, keeping the `no-` prefix.
Here are a few examples:
| Flag                     | Name          | Value   |
| ------------------------ | ------------- | ------- |
| `--no-interaction`       | `interaction` | `false` |
| `--noInteraction`        | `interaction` | `false` |
| `--interaction`          | `interaction` | `true`  |
| `--interaction=false`    | `interaction` | …
=> feat(console): support negative arguments

composer.json
1.2.9 has a problem where it removes doc blocks that should not be removed
=> fix: rector

src/Tempest/Console/src/Components/Interactive/MultipleChoiceComponent.php, src/Tempest/Console/src/Components/Interactive/SearchComponent.php, src/Tempest/Console/src/Components/Interactive/TextBoxComponent.php, src/Tempest/Console/src/Components/Static/StaticConfirmComponent.php, src/Tempest/Console/src/Components/Static/StaticMultipleChoiceComponent.php, src/Tempest/Console/src/Components/Static/StaticSearchComponent.php, src/Tempest/Console/src/Components/Static/StaticSingleChoiceComponent.php, src/Tempest/Console/src/Components/Static/StaticTextBoxComponent.php, src/Tempest/Console/src/Console.php, src/Tempest/Console/src/GenericConsole.php, src/Tempest/Console/src/Initializers/ConsoleInitializer.php, src/Tempest/Console/src/Input/MemoryInputBuffer.php, src/Tempest/Console/src/Testing/ConsoleTester.php, tests/Integration/Console/Components/MultipleChoiceComponentTest.php, tests/Integration/Console/Components/SearchComponentTest.php, tests/Integration/Console/Components/Static/StaticConfirmComponentTest.php, tests/Integration/Console/Components/Static/StaticMultipleChoiceComponentTest.php, tests/Integration/Console/Components/Static/StaticSearchComponentTest.php, tests/Integration/Console/Components/Static/StaticSingleChoiceComponentTest.php, tests/Integration/Console/Components/Static/StaticTextBoxComponentTest.php, tests/Integration/Console/RenderConsoleCommandTest.php
This pull request implements a "no prompt" mode. This mode can be enabled by passing the `--no-interaction` flag to any command.
That mode disables all user interactions with the console. Instead, default values will be used when provided, otherwise `null` or empty arrays will be returned by input components.
To support this mode, some components and their static version needed a new `default` option, which this pull request includes.
Additional changes:
- The `Console` interface has a new `disablePrompting` and `disableTty` method to, well, disable prompting and TTY programmatically.
- The `interactiveSupported` is renamed to `supportsTty`, and `supportsPrompting` has been added. Both have been added to the interface and made public.
- The `ConsoleTester` class has a new …
=> feat(console): support "no prompt" mode

src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/tests/ArrayHelperTest.php
Fixes #684
This pull request fixes exceptions thrown when calling `first` and `last` on an empty `ArrayHelper` instance.
```php
arr()->first(); // null
arr()->last(); // null
```
=> fix(support): support calling `first` and `last` on empty `ArrayHelper`

src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/tests/StringHelperTest.php
This pull request adds support for `wrap` and `unwrap` on `StringHelper`.
```php
str('value')->wrap('[', ']'); // [value]
str('[value]')->unwrap('[', ']'); // value
```
Unwrapping will only work if both ends correspond to the given `before` and `after` arguments. The `strict` argument disables this behavior:
```php
str('Scott Kennedy')->unwrap('Leon ', ' Kennedy', strict: true); // Scott Kennedy
str('Scott Kennedy')->unwrap('Leon ', ' Kennedy', strict: false); // Scott
```
=> feat(support): add `wrap` and `unwrap` to `StringHelper`

src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/tests/ArrayHelperTest.php
This pull request adds support for not specifying a value to `pop` and `unshift`.
```php
arr([1, 2, 3])->pop(); // [1, 2]
arr([1, 2, 3])->unshift(); // [2, 3]
```
=> feat(support): support not specifying a value to `ArrayHelper::pop` and `ArrayHelper::unshift`

src/Tempest/Console/src/Actions/RenderConsoleCommand.php, src/Tempest/Console/src/ConsoleArgument.php, src/Tempest/Console/src/Input/ConsoleArgumentDefinition.php, tests/Fixtures/Console/CommandWithArgumentName.php, tests/Fixtures/Console/CommandWithDifferentArguments.php, tests/Fixtures/Console/Hello.php, tests/Integration/Console/ConsoleArgumentBagTest.php, tests/Integration/Console/Input/ConsoleArgumentDefinitionTest.php, tests/Integration/Console/Middleware/OverviewMiddlewareTest.php
This PR allow `ConsoleArgument` Attribute to have a `name` parameter to override the method parameter name if wanted.
This Fix #588
=> feat(console): add `name` parameter to `#[ConsoleArgument]`

src/Tempest/Http/src/Commands/ServeCommand.php, src/Tempest/Http/src/Commands/router.php
- extends `tempest serve` with a router script to control what it will serve as static file and what will continue through tempest
- The old/current implementation doesn't allow routes with known file extensions (eg `.json`) to hit tempest  even if the file does not exist
- Add an route `#[Get('/example/{file}')]` to a known controller
- run `tempest serve` and try accessing the route through `curl http://localhost:8000/example/my_file.json` 
- On my branch this will work
- On main this will result in a 404 (given that `example/my_file.json` doesn't exist)
=> feat(console): ensure `tempest serve` supports routes with file extension

src/Tempest/Http/src/Routing/Construction/RouteTreeNode.php, src/Tempest/Http/src/Routing/Construction/RoutingTree.php
Refactor the adding of routes to the routing tree by replacing recursion with iteration.
Recursion is pretty inefficient in PHP. This relatively small refactor is roughly 10% faster
```
+------------------------+-----------------------------------------+-----+------+-----+----------+---------+--------+
| benchmark              | subject                                 | set | revs | its | mem_peak | mode    | rstdev |
+------------------------+-----------------------------------------+-----+------+-----+----------+---------+--------+
| RouteConfiguratorBench | benchRouteConfigConstructionRouteAdding |     | 1000 | 5   | 2.100mb  | 1.016ms | ±0.32% |
+------------------------+-----------------------------------------+-----+------+-----+----------+---------+--------+
```
``` …
```
=> perf(routing): replace recursion in favor of iteration

src/Tempest/CommandBus/src/CommandBusConfig.php, src/Tempest/CommandBus/src/CommandHandlerAlreadyExists.php, src/Tempest/CommandBus/tests/Fixtures/CreateUserCommandHandler.php, src/Tempest/CommandBus/tests/GenericCommandBusTest.php
=> fix(commandbus): disallow having two `#[CommandHandler]` for the same command

src/Tempest/Http/src/Commands/ServeCommand.php, src/Tempest/Http/src/Commands/router.php
This https://github.com/tempestphp/tempest-framework/issues/704 pull request added router for `./tempest serve` to correctly handle paths with file extension.
It uses `putenv` but on default php environment `$_ENV` is not populated.
It depends on `php.ini` setting `variables_order` that often is set to `GPCS` instead of `EGPCS`.
But `php` cli allows to set `$_SERVER['DOCUMENT_ROOT']` with `-t` flag, so we can use it to pass public path to router.
=> fix(http): use document root instead of env in `tempest serve`

src/Tempest/Console/src/ConsoleApplication.php, src/Tempest/Http/src/HttpApplication.php
Currently tempest always adds `AppendLogChannel` and hardcoded paths, even if user provided `LogConfig`.
I think better way would be to publish `log.config.php` with sane defaults with framework, but I feel it will bring discussion about project directory structure and probably better to just avoid it for now?
Also, as this code currently lives in `HttpApplication` boot method, I don't feel comfortable with calling this in test.
=> fix(http): use default log config only if no config is provided

src/Tempest/Log/src/GenericLogger.php, src/Tempest/Log/tests/GenericLoggerTest.php
Right now, it isn't possible to correctly declare `AppendLogChannel` more than once in `LogConfig`. It will result in same log, being logged in same channel multiple times.
This changes this behaviour, by storing `Monolog` instance by `spl_object_id`, not class name.
=> feat(log): allow usage of multiple same log channels

src/Tempest/Database/src/Exceptions/InvalidDefaultValue.php, src/Tempest/Database/src/QueryStatements/CreateTableStatement.php, src/Tempest/Database/src/QueryStatements/JsonStatement.php, tests/Integration/Database/QueryStatements/CreateTableStatementTest.php
Part of #547 to add the `json` data type to the table statements
Latest versions of MySQL accept default value for `json` but this require a version check.
I didn't want to add this complexity (at least for this pr) as this was not done either for `text` type before
Do you think we should check if value provided as `default` is a valid json ? `json_validate` seems free to use as Tempest require 8.3+
=> feat(database): add json data type

composer.json, src/Tempest/Console/composer.json, src/Tempest/Console/src/Highlight/DynamicTokenType.php, src/Tempest/Console/src/Highlight/TempestConsoleLanguage/Injections/DynamicInjection.php, src/Tempest/Console/src/Highlight/TempestConsoleLanguage/TempestConsoleLanguage.php, src/Tempest/Console/src/Highlight/TempestTerminalTheme.php, src/Tempest/Console/tests/TempestConsoleLanguage/Injections/DynamicInjectionTest.php, tests/Integration/Console/Highlight/TempestConsoleLanguage/TempestConsoleLanguageTest.php
This pull request adds support for dynamic style injections, responding to the need to write arbitrary styles. 
For context, I have this need in my upcoming "prompts" pull request—I am currently adding injections as I see the need for them, but I need too many colors (eg. `danger`, `warning`, `hint`, `dim`...) which don't really fit the semantic injection paradigm we have now.
Essentially, the following is now possible:
```php
$this->console->write('<style="fg-cyan bg-white underline">Tempest</style>');
```
<details>
<summary>Before edit</summary>
```php
// foreground color
$this->console->write('<fg=cyan>Tempest</fg>');
$this->console->write('<fg=darkcyan>Tempest</fg>');
// background color
$this->console->write('<bg=cyan>Tempest</bg>'); …
```
=> feat(console): support dynamic style injections

src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/src/functions.php, src/Tempest/Support/tests/ArrayHelperTest.php, src/Tempest/Support/tests/StringHelperTest.php
This pull request adds many methods to `ArrayHelper` and `StringHelper`. This is stuff I had the need for when working on an upcoming console components overhaul PR.
Normally, I would send multiple PRs for each change, but there are too many. Reviewing this PR commit-by-commit might be easier.
- `arr(null)` instanciates an empty instance instead of `[null]`
- Added generics to `first` and `last`
- Added `int` support to `get` and `has`
- Added `flatten` and `flatMap`
- Instanciating `StringHelper` with `null` will no longer crash
- Added `replaceAt`, for replacing a portion of a string with another a the specified position
- Added `insert`, which inserts a string at the specified position
- Added `limit`, for truncating a string
- Added `substr`, which proxies `mb_substr`
- Added `take`, …
=> feat(support): add more methods to `ArrayHelper` and `StringHelper`

src/Tempest/Console/src/Actions/RenderConsoleCommand.php, src/Tempest/Console/src/Exceptions/InvalidEnumArgument.php, src/Tempest/Console/src/Input/ConsoleArgumentBag.php, src/Tempest/Console/src/Input/ConsoleArgumentDefinition.php, tests/Integration/Console/ConsoleArgumentBagTest.php, tests/Integration/Console/Fixtures/MyConsole.php, tests/Integration/Console/Fixtures/TestStringEnum.php, tests/Integration/Console/RenderConsoleCommandTest.php
This pull request brings possibility of using enums as command arguments.
So this will be possible
```php
enum Type: string
{
case JSON = 'json';
case TEXT = 'text';
}
class MyCommand
{
#[ConsoleCommand('cmd')]
public function __invoke(Type $type): void {}
}
```
Call
```
./tempest cmd --type=json
```
in case of wrong value:
```
Invalid argument `invalid` for `type` argument, valid values are: json, text
```
And definition will be displayed as
```
cmd <type {json|text}>
```
=> feat(console): accept `BackedEnum` as command arguments

src/Tempest/Http/src/IsRequest.php, src/Tempest/Http/src/Mappers/PsrRequestToRequestMapper.php, src/Tempest/Http/src/Mappers/RequestToPsrRequestMapper.php, src/Tempest/Mapper/src/Mappers/ArrayToObjectMapper.php, tests/Fixtures/Modules/Books/Requests/CreateBookRequest.php, tests/Integration/Mapper/PsrRequestToRequestMapperTest.php
=> feat(http): map uploaded files into the request properties

composer.json, src/Tempest/Console/composer.json, src/Tempest/Console/src/Highlight/DynamicTokenType.php, src/Tempest/Console/src/Highlight/TempestConsoleLanguage/Injections/DynamicInjection.php, src/Tempest/Console/src/Highlight/TempestTerminalTheme.php, src/Tempest/Console/tests/TempestConsoleLanguage/Injections/DynamicInjectionTest.php, src/Tempest/Debug/composer.json, src/Tempest/Http/composer.json, tests/Integration/Console/Highlight/TempestConsoleLanguage/TempestConsoleLanguageTest.php
This pull request is a follow-up of #703. It improves support for nested `<style>` tags and better handles ending tags (`</style>`).
&nbsp;
The first change is the support for nested `<style>` tags. I changed the regular expression to use a negative lookahead (`(?!\<style)`) that prevents matching nested `<style>` tags. Without this, the following would be matched as one block:
```
<style="dim">[<style="fg-cyan">cyan</style>]</style>
```
The replacement would then miss styles. Now, it properly matches two distinct blocks.
&nbsp;
The second change is an update to how `</style>` resets the current style. Instead of using `0m` to reset all styles, it will use more specific reset codes depending on the opening tag.
For instance:
```
<style="dim"><style="fg-gray">dim-gray</style> …
```
=> fix(console): handle nested `style` tags

src/Tempest/Http/src/Delete.php, src/Tempest/Http/tests/Routing/Construction/RouteConfiguratorTest.php
Provide a new attribute for `Delete` method
=> feat(http): add `Delete` attribute

src/Tempest/View/src/Elements/ElementFactory.php, src/Tempest/View/src/Elements/RawElement.php, tests/Integration/View/TempestViewRendererDataPassingTest.php
=> fix(view): attributes for raw elements

src/Tempest/View/src/Components/XForm.php, src/Tempest/View/src/Components/XInput.php, src/Tempest/View/src/Components/XSubmit.php, src/Tempest/View/src/Elements/ElementFactory.php, src/Tempest/View/src/Elements/RawElement.php, tests/Integration/View/TempestViewRendererTest.php, tests/Integration/View/ViewComponentDiscoveryTest.php
Adds the ability to wrap any kind of HTML in `x-raw` so that Tempest's view compiler will ignore it.
=> feat(view): add raw html element

src/Tempest/Database/src/Commands/MakeModelCommand.php, src/Tempest/Http/src/Commands/MakeControllerCommand.php
This PR refactor the `make:controller` parameters name to be easier to read.
Also, to be consistant with other make commands and to avoid another PR for this, I've updated the success message of `make:controller` and `make:model` to be more explicit
=> refactor(console): update `make:controller` command parameters to be simpler

.php-cs-fixer.dist.php
The newest CS fixer update (https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.65.0) adds some new features that make it so more phpdoc types are imported. The problem is that our ORM relies on the FQCN to be present in docblocks. That's why I've made this config adjustment
=> chore: cs-fixer updates

composer.json
As noted in #784, running Rector _after_ PHP CS Fixer can cause the code style check to fail. Switching these two around in the `composer qa` script ensures that Rector runs _first_ (potentially changing code), and PHP CS Fixer comes in _after_ to clean it up and format it.
=> fix: change order of scripts in composer.json

src/Tempest/Http/src/Static/StaticCleanCommand.php, tests/Integration/Http/Static/StaticCleanCommandTest.php
Fixes #777.
I opted to split the functionality out into private methods to keep it nice and readable. If that's unwanted, let me know and I'll change it back to all be contained within the `__invoke()` method.
---
- I also removed the unnecessary `$console` property from the command class. It's injected in the parent class and was unused anyway.
- I also fixed the namespace for the test.
=> fix(http): remove empty directories when running `static:clean`

src/Tempest/Core/src/Kernel/FinishDeferredTasks.php, tests/Integration/Core/DeferredTasksTest.php
This pull request adds support for container-resolved parameter on `defer` closures:
```php
defer(function (AnalyticsService $service, Request $request) {
$service->visit($request);
});
```
=> feat(core): allow `defer` callbacks to receive parameters from container

src/Tempest/Core/src/Kernel.php, tests/Integration/Core/DeferredTasksTest.php
This is a minor refactor that uses `Container#invoke` instead of the usual parenthesis call syntax, which can be missed when reading.
=> refactor(core): call invokable classes with `invoke`

src/Tempest/Debug/src/Debug.php, src/Tempest/Debug/src/ItemsDebugged.php, src/Tempest/Debug/src/functions.php, tests/Integration/Debug/DebugTest.php
Similarly to https://github.com/tempestphp/tempest-framework/pull/795, this pull request adds a `ItemsDebugged` event that is emitted when items are debugged through `Tempest\Debug`.
A new `le` (log event) function has also been added. It doesn't write to `STDOUT` nor a log file.
Very happy to change the name of the event and the function! Please suggest.
=> feat(debug): emit `ItemsDebugged` on debug

src/Tempest/Core/src/Kernel.php, tests/Integration/Core/KernelTest.php
This pull request adds a `TEMPEST_START` constant which holds the system's [high-resolution time](https://www.php.net/manual/en/function.hrtime.php) for performance measuring purposes.
```php
echo (hrtime(true) - TEMPEST_START) * 1e-6; // 244.245834
```
=> feat(core): add `TEMPEST_START` constant

src/Tempest/Framework/Testing/Http/HttpRouterTester.php, src/Tempest/Http/src/Connect.php, src/Tempest/Http/src/Head.php, src/Tempest/Http/src/Options.php, src/Tempest/Http/src/Trace.php, tests/Fixtures/Controllers/TestController.php, tests/Integration/Testing/Http/HttpRouterTesterIntegrationTest.php
When writing documentation for https://github.com/tempestphp/tempest-app/pull/8 I noticed not all HTTP methods are supported by the `HttpRouterTester`. This adds all methods which were already described in `Tempest\Http\Method` enum.
=> feat(framework): extend http testing methods

src/Tempest/Console/src/Components/Interactive/SearchComponent.php, src/Tempest/Console/src/Components/Interactive/SingleChoiceComponent.php, src/Tempest/Console/src/Components/Interactive/TextInputComponent.php, src/Tempest/Console/src/Components/Static/StaticSingleChoiceComponent.php, src/Tempest/Console/src/Console.php, src/Tempest/Console/src/GenericConsole.php, tests/Integration/Console/Components/Static/StaticSingleChoiceComponentTest.php
This pull request adds support for passing a `BackedEnum` FQCN to `Console#ask`'s `options` parameter:
```php
$this->console->ask(
question: 'Pick a value',
options: StringBackedEnum::class,
default: StringBackedEnum::FOO, // supports passing an enum as a default option as well
);
```
=> feat(console): add backed enum support to `ask`

src/Tempest/Console/src/Middleware/InvalidCommandMiddleware.php, tests/Integration/Console/Fixtures/IntEnumCommand.php, tests/Integration/Console/Fixtures/StringEnumCommand.php, tests/Integration/Console/Fixtures/TestIntEnumFromOne.php, tests/Integration/Console/Middleware/InvalidCommandMiddlewareTest.php
This pull request improves the rescuing of backed enum console parameters for console commands. Previously, they were treated as text input. After this PR, they are treated as choices.
https://github.com/user-attachments/assets/936e75d9-bd09-43f9-b8cf-f334c88a96be
Closes #807
=> feat(console): improve rescuing enum console parameters

src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/tests/ArrayHelperTest.php
This pull request adds the `every` method to `ArrayHelper`. It works like the JavaScript one.
```php
arr([2, 4, 6])->every(fn (int $value) => ($value % 2) === 0); // true
```
=> feat(support): add `every` to `ArrayHelper`

src/Tempest/Http/src/Status.php, src/Tempest/Http/tests/StatusTest.php
Fixes https://github.com/tempestphp/tempest-framework/issues/778 .
Somebody has to fix the most important and widely used HTTP statuscodes out there. 
For anybody who doesn't know, [418 is a official HTTP status code](https://www.rfc-editor.org/rfc/rfc2324#section-2.3.2) introduces as an RFC during april fools  by the official networking working committee at that time. I don't know why and how, but it was accepted and it stuck. Recently there was a movement to remove it, but surprise surprise , after more than 10 years not only did people use it. People loved this small easter egg in a rigid spec of the foundation of our internet. 
[Read the RFC](https://www.rfc-editor.org/rfc/rfc2324) if you have the time, it is a proper laugh.
=> fix(http): correct HTTP 418 description and coverage

src/Tempest/Console/src/Actions/ExecuteConsoleCommand.php, src/Tempest/Console/src/Actions/ResolveConsoleCommand.php, src/Tempest/Console/src/Console.php, src/Tempest/Console/src/GenericConsole.php, src/Tempest/Console/src/Input/ConsoleArgumentBag.php, src/Tempest/Console/src/Middleware/ResolveOrRescueMiddleware.php, src/Tempest/Console/src/Testing/ConsoleTester.php, tests/Integration/Console/Actions/ExecuteConsoleCommandTest.php, tests/Integration/Console/Actions/ResolveConsoleCommandTest.php, tests/Integration/Console/Fixtures/CommandWithNonCommandMethods.php, tests/Integration/Console/Middleware/OverviewMiddlewareTest.php, tests/bootstrap.php
This pull request adds support for calling console commands with the following syntaxes:
```php
$this->console->call(MyCommand::class);
$this->console->call([MyCommand::class, 'method']);
$this->console->call(MyCommand::class, arguments: ['arg1', '--flag']);
```
Previously, only the following syntax was allowed:
```php
$this->console->call('my-command arg1 --flag');
```
An inconsistency with `ConsoleTester#call` and `GenericConsole#call` has also been fixed. The former already allowed the FQCN and array syntaxes, while the later did not. They now use the same resolving logic.
Since calling a command with parameters in a single string is still allowed to preserve existing functionalities, there are a lot more changes in this pull request that it could have if the parameters could only be …
=> feat(console): allow calling console commands via fqcn

src/Tempest/Cache/src/CacheClearCommand.php, src/Tempest/Cache/src/CacheStatusCommand.php, src/Tempest/Console/src/Commands/TailDebugLogCommand.php, src/Tempest/Console/src/Commands/TailProjectLogCommand.php, src/Tempest/Console/src/Commands/TailServerLogCommand.php, src/Tempest/Console/src/Middleware/ResolveOrRescueMiddleware.php, src/Tempest/Core/src/Commands/DiscoveryClearCommand.php, src/Tempest/Core/src/Commands/DiscoveryGenerateCommand.php, src/Tempest/Core/src/Commands/DiscoveryStatusCommand.php, src/Tempest/Framework/Commands/ConfigShowCommand.php, tests/Integration/Console/Middleware/ResolveOrRescueMiddlewareTest.php
This pull request adds support for using the `:` shorthand when running console commands.
For instance, typing `tempest ca:cl` will now suggest `cache:clear`. This is a functionality that the Symfony console component has (so does Composer and Laravel).
I use this shorthand all the time, and I thought it was missing in Tempest, especially seeing all these commands with hardcoded shorthands (eg. `cache:clear` -> `cc`).
- With this implementation, Tempest will still ask for confirmation before running a matched command. Should we run the command if there is a sole result?
- Should we remove the hardcoded aliases if so?
https://github.com/user-attachments/assets/158d28c8-7617-43e7-9c35-b90d5253f130
In comparison, here's how it look in Laravel: …
=> feat(console): provide command suggestions when using `:` shorthands

.github/ISSUE_TEMPLATE/bug-report.yml
In the Github bug report issue template, PHP 8.3 was the only available PHP version. Since tempest requires a minimum of 8.4 now, I've updated the option.
=> chore: update issue template to use php 8.4

src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/tests/ArrayHelperTest.php
This pull request fixes `ArrayHelper#get` so that it supports keys with dots in them. Prior to this PR, the following did not pass:
```php
$array = [
'src/main.ts' => '...',
];
$this->assertSame('...', arr($array)->get('src/main.ts'));
```
=> fix(support): support keys with dots in `ArrayHelper#get`

src/Tempest/Support/src/ArrayHelper.php, src/Tempest/Support/tests/ArrayHelperTest.php
This pull request adds the `prepend` and `append` methods to `ArrayHelper`.
```php
arr()
->prepend($first)
->append($last);
```
=> feat(support): add `append` and `prepend` to `ArrayHelper`

src/Tempest/Container/src/Container.php, src/Tempest/Container/src/GenericContainer.php, src/Tempest/Container/tests/ContainerTest.php, src/Tempest/Container/tests/Fixtures/ImplementsInterfaceA.php, src/Tempest/Container/tests/Fixtures/InterfaceA.php
This pull request adds the ability to unregister bindings, as well as checking for the existence of a binding.
```php
$this->container->register(SomeInterface::class, fn () => new SomeImplementation());
$this->container->has(SomeInterface::class); // true
$this->container->unregister(SomeInterface::class);
$this->container->has(SomeInterface::class); // false
```
Both `has` and `unregister` act on normal bindings and singletons. I think it would be pretty uncommon to have both a classic binding and a singleton with the same name, so this avoids having two extra methods for checking the type of the binding.
> [!NOTE]
> The `has` method only checks for the existence of a binding. `has` may return `false` even though `get` would succeed because of autowiring.
=> feat(container): add `has` and `unregister`

src/Tempest/Support/src/HtmlString.php, src/Tempest/Support/src/StringHelper.php, src/Tempest/Support/tests/HtmlStringTest.php, src/Tempest/Support/tests/StringHelperTest.php, src/Tempest/View/src/Renderers/TempestViewRenderer.php, tests/Integration/View/TempestViewRendererTest.php
Second take on https://github.com/tempestphp/tempest-framework/pull/830
---
This pull request introduces a `HtmlString` class. This class can be passed to Tempest's view renderer and its content won't be escaped as for other strings.
It has the ability to be converted to `StringHelper`, and `StringHelper` can also be converted to `HtmlString`:
```php
$html = new HtmlString('<h1></h1>');
$string = $html->toStringHelper();
$html = $string->toHtmlString();
```
It also has a `createTag` static constructor, which creates an HTML tag with properly-parsed attributes:
```php
HtmlString::createTag('script', [
'src' => 'https://localhost:5137/@vite/client',
]);
```
=> feat(support): add `HtmlString` class

src/Tempest/Console/src/Highlight/TempestConsoleLanguage/Injections/LinkInjection.php, src/Tempest/Console/src/Highlight/TempestConsoleLanguage/TempestConsoleLanguage.php, src/Tempest/Console/tests/TempestConsoleLanguage/Injections/LinkInjectionTest.php, tests/Integration/Console/Highlight/TempestConsoleLanguage/TempestConsoleLanguageTest.php
This pull request adds support for printing hyperlinks, with a simple `href` syntax:
```php
$this->console->writeln(
'Visit the <href="https://tempestphp.com">Tempest website</href> for more information.'
);
```
On supporting terminals, the "Tempest website" part will be clickable.
=> feat(console): add support for printing hyperlinks

src/Tempest/Console/src/Commands/MakeConfigCommand.php, src/Tempest/Console/src/Enums/ConfigType.php, src/Tempest/Console/src/Stubs/blade.config.stub.php, src/Tempest/Console/src/Stubs/cache.config.stub.php, src/Tempest/Console/src/Stubs/command-bus.config.stub.php, src/Tempest/Console/src/Stubs/console.config.stub.php, src/Tempest/Console/src/Stubs/database.config.stub.php, src/Tempest/Console/src/Stubs/event-bus.config.stub.php, src/Tempest/Console/src/Stubs/log.config.stub.php, src/Tempest/Console/src/Stubs/twig.config.stub.php, src/Tempest/Console/src/Stubs/view.config.stub.php, src/Tempest/Database/src/Builder/ModelQueryBuilder.php, src/Tempest/Database/src/QueryStatements/AlterTableStatement.php, src/Tempest/Database/src/QueryStatements/CreateTableStatement.php, src/Tempest/Generation/src/DataObjects/StubFile.php, tests/Integration/Console/Commands/MakeConfigCommandTest.php, tests/Integration/Database/Builder/ModelQueryBuilderTest.php, tests/Integration/Database/QueryTest.php
This PR add the `make:config` command
This close a TODO on #759 
I have created a config type enum to have a list of supported config type, similar to #804 
So it supports all of these config types : 
- database
- twig
- blade
- view
- event-bus
- command-bus
- log
- cache
- console
I'm not really familiar with all components so please give me feedbacks on related stub files, I have stick as much as possible to the doc 😄 
Notice that I didn't add a support for `AppConfig` it is because the doc seems to be outdated as params are no longer the same as the current codebase and I'm not sure that we can create a custom `AppConfig` or if this is only internal ( have seen a default one which take env variables )
Also checked the `FrameworkInstaller` which don't seems to create a default …
=> feat(console): add `make:config` command

src/Tempest/Vite/src/Vite.php
When using `vite_tags()` in templates, the argument will be `null` by default. I think that's a bug in the views implementation, but I took the opportunity to fix `getTags` to handle that situation anyway.
=> fix(vite): fall back to global entrypoints if supplied ones are empty

src/Tempest/Database/src/QueryStatements/CreateTableStatement.php
Something small I encountered while working on a hobby project.
I wanted to add a timestamp column, but don't have the time to create a proper statement specific class for it.
So I thought this might be a nice little nugget.
=> feat(database): add `raw` to `CreateTableStatement`

composer.json, phpstan.neon.dist, src/Tempest/Generation/src/Exceptions/FileGenerationException.php, src/Tempest/Generation/src/Exceptions/FileGenerationFailedException.php, tests/Architecture/ArchitectureTestCase.php
phpat supports phpstan 2 
- Re-add phpat based on the deletion in https://github.com/tempestphp/tempest-framework/pull/821
- I needed to change one extra file: src/Tempest/Generation/src/Exceptions/FileGenerationFailedException.php, it was newly introduced after the removal of phpat and it did not adhere to our final rules. I checked the catch statements where the extended clauses where used and this change shouldn't affect it.
=> chore: add back php architecture tests

src/Tempest/Database/src/BelongsTo.php, src/Tempest/Database/src/Builder/ModelDefinition.php, src/Tempest/Database/src/Builder/Relations/BelongsToRelation.php, src/Tempest/Database/src/Builder/Relations/HasManyRelation.php, src/Tempest/Database/src/HasMany.php, src/Tempest/Database/tests/Relations/BelongsToRelationTest.php, src/Tempest/Database/tests/Relations/Fixtures/BelongsToParentModel.php, src/Tempest/Database/tests/Relations/Fixtures/BelongsToRelatedModel.php, src/Tempest/Database/tests/Relations/HasManyRelationTest.php
Fixes https://github.com/tempestphp/tempest-framework/issues/756
- Adds explicit relation attributes for HasMany and BelongsTo
- Add tests for both explicit and implicit relation definitions
- I implemented it by "database" reference. So you supply the inverse and local database field names. Is this what we want? Or is it preferred to supply the inverse property name and infer the sql name from that?
- If / when approved I will create an PR for the docs repo.
=> feat(database): add explicit relation attributes

src/Tempest/Validation/src/Rules/IP.php, src/Tempest/Validation/src/Rules/IPv4.php, src/Tempest/Validation/src/Rules/IPv6.php, src/Tempest/Validation/tests/Rules/IPv6Test.php
This PR aims to fix the issue that came with PHP 8.4.3 regarding reserved IPv6 address handling. From PHP 8.4.3, you need to add an additional flag to allow checking for global reserved IPv6 addresses, otherwise only local ones will be taken into account (for example `::1`).
=> fix(tests): update IPv6 test to align with PHP 8.4.3 behavior

.github/workflows/create-gh-release.yml, .github/workflows/publish-javascript-packages.yml, bin/release, cliff.toml, composer.json, eslint.config.mjs, src/Tempest/Core/src/Kernel.php
This pull request attempts to make the release script actually usable. To do this, we need:
- ~~To implement `bumpPhpPackages` and `cleanUpAfterRelease`.~~
The release script will:
Related: https://github.com/tempestphp/tempest-framework/pull/587, https://github.com/tempestphp/tempest-framework/issues/676
=> ci: improve release script

src/Tempest/Core/src/Commands/InstallCommand.php, src/Tempest/Vite/src/Installer/Tailwind/main.css, src/Tempest/Vite/src/Installer/Tailwind/main.ts, src/Tempest/Vite/src/Installer/Tailwind/vite.config.ts, src/Tempest/Vite/src/Installer/ViteInstaller.php
This pull request adds the ability to install Tailwind CSS when using the `vite` installer. By default, a question will be asked to the user, but the `--tailwind` flag bypasses the prompt.
https://github.com/user-attachments/assets/b01d4ae6-7c83-490e-9075-cc1f4989d7e1
The Tailwind CSS installation uses the Vite implementation, installing both `tailwindcss` and `@tailwindcss/vite`.
Closes https://github.com/tempestphp/tempest-framework/issues/917
=> feat(vite): add Tailwind CSS option to the installer

src/Tempest/Mapper/src/Attributes/MapFrom.php, src/Tempest/Mapper/src/Attributes/MapTo.php, src/Tempest/Mapper/src/Mappers/ArrayToObjectMapper.php, src/Tempest/Mapper/src/Mappers/ObjectToArrayMapper.php, src/Tempest/Reflection/src/PropertyReflector.php, tests/Integration/Mapper/Fixtures/ObjectWithMapFromAttribute.php, tests/Integration/Mapper/Fixtures/ObjectWithMapToAttribute.php, tests/Integration/Mapper/Fixtures/ObjectWithMapToCollisions.php, tests/Integration/Mapper/Fixtures/ObjectWithMapToCollisionsJsonSerializable.php, tests/Integration/Mapper/Fixtures/ObjectWithMappedVariousPropertyScope.php, tests/Integration/Mapper/MapperTest.php
This closes #877 
It adds both Attributes. I have a couple of notes here
I don't know if my tests are properly located, maybe they should go in specific `MapperTestCase` class ?
( for `MapTo` )
Due to a weird native array cast for private/protected properties, For now I only keep public properties  
So they're collected from the `ClassReflector` instead of the native array cast ( `jsonSerialize()` remains a priority )  
https://www.php.net/manual/en/language.types.array.php#language.types.array.casting  
I don't really know how we want to deal with private/protected properties then  
I mainly work on `ObjectToArrayMapper` and `ArrayToObjectMapper`  
It seems like the json versions uses those internally so I think I've covered all "object" things
Now, in technical aspect, I've used the …
=> feat(mapper): add `MapFrom` and `MapTo` attributes

bin/release
This fixes the automatic replacement of the `VERSION` constant in the kernel, which is now typed.
=> ci: update kernel version replacement logic

src/Tempest/Database/src/Builder/ModelQueryBuilder.php, src/Tempest/Database/src/Virtual.php, tests/Fixtures/Models/AWithVirtual.php, tests/Integration/ORM/IsDatabaseModelTest.php
Fixes #962
Example use-case where I have a JSON `config` column and I just want a handy readonly accessor for values in it:
```php
<?php
namespace App\Models;
use Tempest\Database\Virtual;
use Tempest\Database\DatabaseModel;
use Tempest\Database\IsDatabaseModel;
final class MyModel implements DatabaseModel
{
use IsDatabaseModel;
#[Virtual]
public string $url
{
get => $this->config['url'] ?? '';
}
public function __construct(
public string $name,
public ?array $config,
)
{ }
}
```
^ in this case I mark the `$url` property with `Virtual` so that `ModelQueryBuilder` doesn't include it in the SELECT clause of queries against this model
=> feat(database): add a `Virtual` attribute to exclude model properties from query builder

src/Tempest/Router/src/Input/InputStream.php, src/Tempest/Router/src/Input/InputStreamInitializer.php, src/Tempest/Router/src/Input/StdinInputStream.php, src/Tempest/Validation/src/SkipValidation.php, src/Tempest/Validation/tests/Fixtures/ObjectWithObjectProperty.php, src/Tempest/Validation/tests/Fixtures/ObjectWithSkipValidation.php, src/Tempest/Validation/tests/Fixtures/ObjectWithStringProperty.php, src/Tempest/Validation/tests/Fixtures/ValidateObjectA.php, src/Tempest/Validation/tests/Fixtures/ValidateObjectB.php, src/Tempest/Validation/tests/Fixtures/ValidateObjectC.php, src/Tempest/View/src/Elements/ViewComponentElement.php, src/Tempest/View/src/ViewComponentDiscovery.php, src/Tempest/View/src/ViewProcessor.php, src/Tempest/View/src/ViewProcessorDiscovery.php, tests/Integration/View/ViewComponentDiscoveryTest.php, tests/Integration/View/x-auto-registered-with-declaration.view.php, tests/Integration/View/x-auto-registered.view.php
Closes #1017
This pull request adds backwards compatibility to components that use `<x-component>` to declare themselves.
=> fix(view): support `<x-component>` in auto-registered components

.env.example, src/Tempest/Cache/src/CacheConfig.php, src/Tempest/Cache/src/IconCache.php, src/Tempest/Console/src/Testing/ConsoleTester.php, src/Tempest/View/src/Components/Icon.php, src/Tempest/View/src/Config/icon.config.php, src/Tempest/View/src/IconConfig.php, tests/Integration/Cache/CacheClearCommandTest.php, tests/Integration/View/IconComponentTest.php
This PR adds a new `x-icon` component.
```html
<x-icon name="ph:eye" class="size-5 text-zinc-500" />
```
On first render, the icon is downloaded from Iconify, and cached indefinitely. On subsequent renders, the icon is pulled from the cache instead of the Iconify API.
The component accepts the following props:
- `name`: The name of the component, in the format `{prefix}:{name}`
- `class`: The class attribute to set on the underlying `svg` HTML element
This PR doesn't include documentation for the component, but I plan to send an other PR to address it.
Closes #1002
=> feat(view): add icon component

src/Tempest/Vite/src/TagsResolver/ManifestTagsResolver.php, tests/Integration/Vite/ManifestTagsResolverTest.php, tests/Integration/Vite/ViteTagsComponentTest.php, tests/Integration/Vite/ViteTest.php
This pull request fixes the generation of asset URLs in Vite by making them absolute, relative to the root.
There is no "asset url" option right now, but open to add it in the future when someone first needs it.
=> fix(vite): generate absolute asset urls

src/Tempest/Validation/src/Rules/IsString.php, src/Tempest/Validation/tests/Rules/IsStringTest.php
- Updated `IsString::isValid()` to accept `Stringable` objects.  
- Added a test case in `IsStringTest` to verify `Stringable` support.  
Fixes [[#989](https://github.com/tempestphp/tempest-framework/issues/989)]
=> feat(validation): allow `Stringable` objects in `IsString` rule

src/Tempest/Router/src/IsRequest.php, src/Tempest/Router/src/Mappers/PsrRequestToGenericRequestMapper.php, src/Tempest/Router/src/Mappers/RequestToPsrRequestMapper.php, src/Tempest/Router/src/Request.php, src/Tempest/Router/src/RequestHeaders.php, src/Tempest/Router/tests/GenericRequestTest.php
Fixes #1006 .
- Ensures all headers keys are lowercased when constructing the request and when retrieving the values from the headers
1. Have a controller with this method
```
#[Get('/headers')]
public function headers(Request $request): Response {
return new Ok([
'host' => $request->headers['host'] ?? null,
'Host' => $request->headers['Host'] ?? null,
]);
}
```
2. Call the method and see as a result `{"host":"localhost:8000","Host":"localhost:8000"}`. 
1. I did not yet do any work on the cookie retrieval. I will do that in a later PR. The reason being, the cookies in a request are accessed through the container instead of passing them through (like any other array). I think I might rework that in one go.
=> feat(http): fix http header casing on retrieval

src/Tempest/Support/src/Str/ManipulatesString.php, src/Tempest/Support/tests/Str/ManipulatesStringTest.php
This pull request adds `basename` support to string utils:
```php
str('path/to/file.txt')->basename()->toString() // file.txt
```
=> feat(support): add `basename` to string utils

composer.json, src/Tempest/Support/composer.json, src/Tempest/Support/src/Str/ManipulatesString.php, src/Tempest/Support/src/Str/functions.php, src/Tempest/Support/tests/Str/ManipulatesStringTest.php
This pull request adds `slug`, `ascii` and `isAscii` as methods to the string utils, as well as individual functions.
They all use the reliable [voku/portable-ascii](https://github.com/voku/portable-ascii) library under the hood.
=> feat(support): add `slug`, `ascii` and `isAscii` to string utils

src/Tempest/Validation/src/Rules/Alpha.php, src/Tempest/Validation/src/Rules/AlphaNumeric.php, src/Tempest/Validation/src/Rules/Numeric.php, src/Tempest/Validation/src/Rules/RegEx.php, src/Tempest/Validation/src/Rules/Time.php, src/Tempest/Validation/src/Rules/Ulid.php, src/Tempest/Validation/src/Rules/Uuid.php, src/Tempest/Validation/tests/Rules/AlphaNumericTest.php, src/Tempest/Validation/tests/Rules/AlphaTest.php, src/Tempest/Validation/tests/Rules/RegexTest.php, src/Tempest/Validation/tests/Rules/TimeTest.php, src/Tempest/Validation/tests/Rules/UlidTest.php, src/Tempest/Validation/tests/Rules/UuidTest.php
**Summary:**
This PR adds a check to ensure the value passed to `preg_match` is a string in various validation rules, preventing a `TypeError` when non-string values (e.g., arrays, booleans, or objects) are provided.
**Changes:**
- Added type checks for string values in the **Alpha**, **AlphaNumeric**, **Numeric**, **RegEx**, **Time**, **Ulid**, and **Uuid** validation rules.
- Updated tests to ensure invalid types return `false` instead of causing a `TypeError`.
**Purpose:**
To prevent errors when non-string values are passed to `preg_match` and improve the stability of the validation rules.
=> fix(validation): prevent type errors in rules using `preg_match`

src/Tempest/Mapper/src/Mappers/StringToStringableMapper.php, src/Tempest/Support/src/Arr/ManipulatesArray.php, src/Tempest/Support/src/Arr/functions.php, src/Tempest/Support/tests/Arr/ManipulatesArrayTest.php, tests/Integration/Support/ArrayTest.php
This pull request adds support for using the mapper on the first or last element of an array:
```php
arr(glob(__DIR__ . "/content/{$version->value}/{$category}/*.md"))
->map(fn (string $path) => before_first(basename($path), '.'))
->sort()
->mapFirstTo(ImmutableString::class)
->title();
```
=> feat(support): add `mapFirstTo` and `mapLastTo` to array utils

src/Tempest/View/src/Renderers/TempestViewCompiler.php, tests/Integration/View/ViewComponentTest.php
This pull request fixes an issue where minified HTML that contained void tags would get broken, due to the conversion of self-closing tag selecting the parents tags as well.
To be more specific, here is what the previous regex, `/<(?<element>\w.*?)\/>/`, would select on the following snippet:
**Snippet**
```html
<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M7 9.667A2.667 2.667 0 0 1 9.667 7h8.666A2.667 2.667 0 0 1 21 9.667v8.666A2.667 2.667 0 0 1 18.333 21H9.667A2.667 2.667 0 0 1 7 18.333z"/><path d="M4.012 16.737A2 2 0 0 1 3 15V5c0-1.1.9-2 2-2h10c.75 0 1.158.385 1.5 1"/></g></svg>
```
**Match from regex**
```html
<svg …
```
=> fix(view): prevent compiling parent elements of minified void tags

src/Tempest/Discovery/src/Commands/MakeDiscoveryCommand.php, src/Tempest/Discovery/src/Stubs/DiscoveryStub.php, tests/Integration/Discovery/Commands/MakeDiscoveryCommandTest.php
This PR checks a TODO on #759 
It adds a command to make a custom discovery  
I kept it simple as the raw file discovery is probably a 1% use case and well-documented  
I think it deserve its own command even if it's like other concepts only an interface + trait, but the stub helps to build faster the discover/apply methods without checking the docs
=> feat(console): add `make:discovery` command

src/Tempest/Console/src/Commands/MakeGeneratorCommandCommand.php, src/Tempest/Console/src/Stubs/GeneratorCommandStub.php, tests/Integration/Console/Commands/MakeGeneratorCommandCommandTest.php
This PR checks a TODO on #759 
It adds a command to make other generator commands
The main difference with a classic command is that it use the `PublishesFiles` trait  
The main method also have a "classic" skeleton of what I usually use to make internal make commands, this must be seen as a faster starter to make a generator-command
=> feat(console): add `make:generator-command` command

src/Tempest/Core/src/Kernel/LoadDiscoveryClasses.php
Apparently, `RecursiveDirectoryIterator` does not yield canonical paths. This pull request ensures that `discoverPath` gets the actual canonical path to the file.
This shouldn't break anything, but I would like you to double-check @brendt before merging
=> fix(discovery): pass real paths to discovery classes

src/Tempest/View/src/Renderers/BladeInitializer.php, src/Tempest/View/src/Renderers/TwigConfig.php, tests/Integration/View/BladeViewRendererTest.php, tests/Integration/View/TwigViewRendererTest.php
This pull requests updates the default Twig and Blade configurations so that the cache paths are relative to Tempest's internal storage, avoiding the need for userland to make a choice as to where to store these caches.
=> feat(view): cache Blade and Twig templates in internal storage

src/Tempest/Database/src/IsDatabaseModel.php, src/Tempest/Database/src/TableName.php, tests/Integration/ORM/IsDatabaseModelTest.php, tests/Integration/ORM/Models/AttributeTableNameModel.php, tests/Integration/ORM/Models/BaseModel.php, tests/Integration/ORM/Models/StaticMethodTableNameModel.php
This pull request offers the ability to specify table names through attributes:
```php
#[TableName('aircraft')]
final class Aircraft implements DatabaseModel
{
use IsDatabaseModel;
}
```
This was already possible through overriding the static `table` method, but this way is less verbose and feels more like Tempest.
=> feat(database): allow overriding table names through model class attributes

src/Tempest/View/src/Commands/ClearViewCacheCommand.php
This pull request adds a `view:clear` command that clears the view cache. This is an alternative to using `cache:clear` and manually selecting the view cache.
Closes https://github.com/tempestphp/tempest-framework/issues/1065
=> feat(view): add `view:clear` command

src/Tempest/Framework/Testing/IntegrationTest.php
The current default behavior during tests is to try to look for a manifest file to generate Vite tags with, which is generally a bad idea because this file is not supposed to exists.
This pull request fixes that by disabling tag resolution by default, so tests can pass without a manifest error being triggered.
=> feat(vite): disable tag resolution in tests by default

src/Tempest/Support/src/Str/ManipulatesString.php, src/Tempest/Support/src/Str/functions.php, src/Tempest/Support/tests/Str/ManipulatesStringTest.php
This pull request slightly improves the quality of life of string manipulation methods by allowing arrays as parameters in some of them.
```php
str('Jon Doe')->contains(['Jon', 'Billy']);
```
=> feat(support): support array parameters in string manipulations

src/Tempest/Support/src/Arr/ManipulatesArray.php, src/Tempest/Support/src/Arr/functions.php
`Arr\map` was changed to `Arr\map_array` in https://github.com/tempestphp/tempest-framework/pull/1045 in order to not conflict with `Tempest\map`, which was understandably frustrating when auto-importing with IDEs.
However, the new name feels like a cheap version of the existing `array_map`. Having `array_map` and `map_array` available feels quite awkward.
`map_iterable` as a name makes a clearer distinction with `array_map`.
=> feat(support): rename `map_array` to `map_iterable`

src/Tempest/Database/src/Config/database.config.php
This pull request updates the location of the default SQLite database to put it in the internal storage, instead of being nested into the vendor directory.
=> feat(database): store default sqlite database in internal storage

src/Tempest/Support/src/Regex/functions.php, src/Tempest/Support/src/Str/ManipulatesString.php, src/Tempest/Support/tests/Regex/FunctionsTest.php, src/Tempest/Support/tests/Str/ManipulatesStringTest.php, src/Tempest/View/src/Elements/PhpForeachElement.php, src/Tempest/View/src/Renderers/TempestViewCompiler.php
This pull request improves our regular expression utilities.
When they were first added, it was mostly to improve the error handling of `preg_` functions. This iteration offers a better API than simple wrappers.
The most common use for `preg_match` is to return a specific group, named or not. This is what `get_match` does:
```php
Regex\get_match('10-abc', '/(?<id>\d+)-.*/'); // 10 (first match by default)
Regex\get_match('10-abc', '/(?<id>\d+)-.*/', match: 'id'); // 10
Regex\get_match('abc', '/(?<id>\d+)-.*/', match: 'id', default: 1); // 1
```
Next, `get_all_matches` is almost the same as `preg_match_all`, but it always uses `PREG_SET_ORDER` for better grouping, and filters out keys not specified in `matches`.
```php
Regex\get_all_matches(
subject: …
```
=> refactor(support): improve regular expression utilities

src/Tempest/Router/src/GenericRouter.php
This pull request allows returning string and arrays directly from controllers. Both the `ResponseSender` and `Response` classes already supported it already, but not the router's `createResponse`, so this PR changes that.
```php
#[Get('/')]
public function __invoke(): string
{
return 'hello world'; // no longer throws!
}
```
=> feat(router): support returning `string` and `array` from controllers

src/Tempest/Support/src/Arr/ManipulatesArray.php, src/Tempest/Support/src/Arr/functions.php, src/Tempest/Support/tests/Arr/ManipulatesArrayTest.php
This pull request adds a `$default` parameter to the array `first` and `last` methods.
```php
arr([])->first(default: 'fallback');
```
=> feat(support): support `$default` on array `first` and `last` methods

.github/workflows/integration-tests.yml
Coveralls was on maintenance today, marking tests as failed in CI because the upload job fails. I don't believe CI should fail because of this.
=> ci: prevent coveralls failures from failing tests

src/Tempest/Database/src/Builder/ModelDefinition.php, src/Tempest/Database/src/Builder/ModelInspector.php, src/Tempest/Database/src/Table.php, tests/Fixtures/Models/A.php, tests/Fixtures/Models/AWithEager.php, tests/Fixtures/Models/AWithLazy.php, tests/Fixtures/Models/AWithValue.php, tests/Fixtures/Models/AWithVirtual.php, tests/Fixtures/Models/B.php, tests/Fixtures/Models/BWithEager.php, tests/Fixtures/Models/C.php, tests/Integration/Database/Relations/Fixtures/BelongsToParentModel.php, tests/Integration/Database/Relations/Fixtures/BelongsToRelatedModel.php, tests/Integration/Database/Relations/Fixtures/HasOneInvalidRelatedModel.php, tests/Integration/Database/Relations/Fixtures/HasOneParentModel.php, tests/Integration/Database/Relations/Fixtures/HasOneRelatedModel.php, tests/Integration/ORM/Models/AttributeTableNameModel.php, tests/Integration/ORM/Models/ChildModel.php, tests/Integration/ORM/Models/ParentModel.php, tests/Integration/ORM/Models/StaticMethodTableNameModel.php, tests/Integration/ORM/Models/ThroughModel.php
The idea behind this is to give the `Table` attribute more flexibility - in case more things need to be added to it in the future.
A good example I can think of right now is `schema` - a concept very commonly used in SQL Server, for example.
Having one attribute per table thing can become terrible real quick.
For example, this:
```php
#[Table(name: 'tweets', schema: 'blogging')]
class Post
{
}
```
is a lot better than this:
```php
#[TableName('tweets')]
#[TableSchema('blogging')]
class Post
{
}
```
=> refactor(database): rename `TableName` to `Table`

src/Tempest/EventBus/src/Testing/EventBusTester.php, src/Tempest/EventBus/src/Testing/FakeEventBus.php, src/Tempest/Framework/Testing/IntegrationTest.php, tests/Integration/EventBus/EventBusTesterTest.php, tests/Integration/EventBus/Fixtures/FakeEvent.php
This pull request adds a new `EventBusTester` class, with an associated property in `IntegrationTest`. It allows faking the event bus, preventing handlers from being called, and enabling assertions on dispatches and listeners.
```php
$this->eventBus->fake(); // register `FakeEventBus` as a singleton for `EventBus`
$this->eventBus->assertDispatched('my-event');
$this->eventBus->assertDispatched(MyEvent::class);
$this->eventBus->assertDispatched(new MyEvent());
$this->eventBus->assertNotDispatched('my-event');
$this->eventBus->assertListeningTo('my-event');
```
`assertDispatched` has optional `count` and `callback` arguments, the former asserting a specific number of dispatches, and the later accepting a callback that should return `false` if some conditions don't match.
I'll add …
=> feat(event-bus): add event bus testing utilities

src/Tempest/Mapper/src/Mappers/ObjectToArrayMapper.php, tests/Integration/Mapper/Fixtures/ObjectWithNullableProperties.php, tests/Integration/Mapper/Mappers/ObjectToArrayMapperTestCase.php
Fixes #1077 
The **ObjectToArrayMapper** does not take into account if a property is null when trying to retrieve a Serializer for it. If a property has a null value, the mappers should map that directly instead of trying to obtain the serializer for its type, otherwise a `CannotSerializeValue` exception is thrown when the property is perfectly mappable (from null to null). This is already the behaviour observed in **ModelToQueryMapper**.
In **ObjectToArrayMapper**, line **48**:
```php
$propertyValue = $property->getValue($object);
if ($propertyValue !== null && ($serializer = $this->serializerFactory->forProperty($property)) !== null) {
return $serializer->serialize($propertyValue);
}
return $propertyValue;
```
Create a class with a nullable property:
```php
use DateTimeImmutable;
use …
```
=> fix(mapper): properly serialize nullable properties in objects

src/Tempest/Container/src/Commands/ContainerShowCommand.php, src/Tempest/Container/src/GenericContainer.php, tests/Integration/Container/Commands/ContainerShowCommandTest.php
This pull request adds a `container:show` console command that lists container definitions, singletons, and initializers. This is useful for debugging, I've needed that several times.
=> feat(container): add `container:show` command

composer.json, src/Tempest/Validation/composer.json
Use https://github.com/giggsey/libphonenumber-for-php-lite instead of full version as the framework is only using it for validation.
Thanks to @natanaelsinisalo for bringing it up.
=> refactor(validation): use lite version of `libphonenumber-for-php`

src/Tempest/Support/src/JavaScript/DependencyInstaller.php, tests/Integration/Support/DependencyInstallerTest.php
Not sure why, but the empty `""` string in the command breaks installing non-dev dependencies when using bun.
=> fix(support): non-dev bun dependencies installation

composer.json, src/Tempest/View/src/Elements/ElementFactory.php, src/Tempest/View/src/Elements/GenericElement.php, src/Tempest/View/src/Elements/PhpDataElement.php, tests/Integration/View/TempestViewRendererTest.php, tests/Integration/View/ViewComponentTest.php
>[!WARNING]
>**This PR does NOT contain the fix - just the failing tests**
Currently, if you have `@` or `:` in an HTML component, the render removes the `@` and replaces the `:` with `-`. Examples:
```html
<button @click="alert('Hello World!')">
<button click="alert('Hello World!')">
```
```html
<button x-on:click="alert('Hello World!')">
<button x-on-click="alert('Hello World!')">
```
This breaks libraries such as alpine, htmx, etc.
Fixes #1126
=> fix(view): `:` is replaced by `-` and `@` is removed

src/Tempest/Console/src/Components/Renderers/KeyValueRenderer.php, src/Tempest/Console/src/Console.php, src/Tempest/Console/src/GenericConsole.php, src/Tempest/Router/src/Commands/RoutesCommand.php, tests/Integration/Console/Renderers/KeyValueRendererTest.php
This pull request updates the `Console#keyValue` method to allow using the available terminal width instead of the predefined 125 characters length.
The `routes:list` command has also been updated to use this option, since the space is needed.
=> feat(console): add option to use terminal width to render key/values

src/Tempest/View/src/Elements/IsElement.php, tests/Integration/View/TempestViewRendererTest.php, tests/Integration/View/ViewComponentTest.php
When looping in a tag, like `<div :foreach="$iterable as $value"`, `$value` cannot be used within the same tag in an attribute.
Example:
```html
<a :foreach="$links as $link" :href="$link->uri">
{{ $link->label }}
</a>
```
In the example above, the link tag will be rendered with the label, but the `href` attribute will be missing.
~Alternative solution: allow for using [`<template>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/template) for things such as `:foreach` and `:if`, etc. It's better than wrapping things in `div` because `template` doesn't get rendered as a tag itself in the page.~
~Currently, in Tempest, `<template>` and everything in it is not rendered at all.~
_Never mind, Tempest has `<x-template>` 😅_ 
Fixes #1157
=> feat(view): attribute precedence

src/Tempest/View/src/Elements/PhpDataElement.php, tests/Integration/View/TempestViewRendererDataPassingTest.php, tests/Integration/View/ViewComponentTest.php
When you have a view (or a component) that has the variable `$items` in it, you can only pass it to one component - after that, the variable is `null`'ed.
Here's an example:
```html
{!! json_encode($items) !!} 
<x-my-aside :items="$items" />
{!! json_encode($items) !!} 
```
Because of that, this becomes impossible to do:
```html
<x-my-aside :items="$items" />
<x-my-main :items="$items" />
<x-my-footer :items="$items" />
```
=> fix(view): prevent `$var` from being `null`ed after passing to component

src/Tempest/View/src/Elements/IsElement.php, tests/Integration/View/TempestViewRendererCombinedExpressionsTest.php, tests/Integration/View/TempestViewRendererTest.php
This is an attempt to fix #1167
Instead of sorting all attributes, we now only pull out `:if` and `:foreach`, and push them to the end of the attribute list, keeping their relative order. This way you can make both combinations, while ensure `:if` and `:foreach` are always last, thus having access to all other data defined on the element.
@wryk @innocenzi would like your input
=> fix(view): improved attribute precedence

composer.json, src/Tempest/Database/src/Builder/QueryBuilders/CountQueryBuilder.php, src/Tempest/Database/src/Builder/QueryBuilders/QueryBuilder.php, src/Tempest/Database/src/Exceptions/CannotCountDistinctWithoutSpecifyingAColumn.php, src/Tempest/Database/src/QueryStatements/CountStatement.php, src/Tempest/Database/tests/QueryStatements/CountStatementTest.php, tests/Integration/Database/Builder/CountQueryBuilderTest.php
This pull request introduces a new `CountQueryBuilder` to the Tempest database library, enabling efficient SQL `COUNT` queries with fluent condition chaining. It includes the implementation of the builder, integration with existing query builders, and comprehensive unit and integration tests.
* Added the `CountQueryBuilder` class to support building SQL `COUNT` queries with methods for chaining conditions (`where`, `andWhere`, `orWhere`, etc.) and specifying columns. It integrates with `ModelDefinition` and `TableDefinition` for resolving table and field details. (`src/Tempest/Database/src/Builder/QueryBuilders/CountQueryBuilder.php`)
* Introduced a `count()` method in the `QueryBuilder` class to create instances of `CountQueryBuilder`, allowing seamless integration with existing query …
=> feat(database): add `Count` query builder and statement

packages/container/src/Container.php, packages/container/src/GenericContainer.php, packages/container/tests/ContainerTest.php, packages/storage/composer.json, packages/storage/src/Config/AzureStorageConfig.php, packages/storage/src/Config/CustomStorageConfig.php, packages/storage/src/Config/FTPStorageConfig.php, packages/storage/src/Config/GoogleCloudStorageConfig.php, packages/storage/src/Config/InMemoryStorageConfig.php, packages/storage/src/Config/LocalStorageConfig.php, packages/storage/src/Config/R2StorageConfig.php, packages/storage/src/Config/S3StorageConfig.php, packages/storage/src/Config/SFTPStorageConfig.php, packages/storage/src/Config/StorageConfig.php, packages/storage/src/Config/ZipArchiveStorageConfig.php, packages/storage/src/StorageInitializer.php, packages/storage/src/Testing/RestrictedStorageInitializer.php, packages/storage/src/Testing/StorageTester.php, packages/storage/src/Testing/TestingStorage.php, packages/storage/tests/StorageTest.php, tests/Integration/Container/Commands/ContainerShowCommandTest.php, tests/Integration/Storage/MultipleStoragesTest.php, tests/Integration/Storage/StorageTesterTest.php
This pull request adds support for multiple storage by adding the `HasTag` interface to the `StorageConfig` and by adapting the testing helpers.
The latter required the addition of `removeInitializer` to the container, as well as updating `unregister` to support unregistering the dependency along with all its tagged instances.
**Note**: this should be merged after the refactor in https://github.com/tempestphp/tempest-framework/pull/1186, I'll solve the conflicts myself.
=> feat(storage): support multiple storage configurations

packages/support/src/Filesystem/functions.php, packages/support/tests/Filesystem/UnixFunctionsTest.php
Attempting to remove a symbolic link pointing to an invalid (non-existing) file caused an error because `file_exists($x)` returns `false` in such a case.
I noticed this because without this change `phpunit` crashes with errors on my OS, my guess is that this is related to the order in which files are removed from the directory during tests.
=> fix(filesystem): add ability to delete invalid symlinks

packages/console/src/Testing/ConsoleTester.php, packages/router/src/Static/Exceptions/DeadLinksDetectedException.php, packages/router/src/Static/StaticGenerateCommand.php, packages/storage/composer.json, tests/Integration/Http/Static/Fixtures/StaticPageController.php, tests/Integration/Http/Static/StaticGenerateCommandTest.php
Closes https://github.com/tempestphp/tempest-framework/issues/1101
This pull request implements dead link detection when running `static:generate`. Using `--allow-dead-links` skips this process. Adding `{:ssg-ignore="true"}` to a link ignores that link explicitely.
I'll write tests after https://github.com/tempestphp/tempest-framework/pull/1186
=> feat(router): detect dead links when generating static pages

src/Tempest/Framework/Commands/ConfigShowCommand.php, tests/Integration/Framework/Commands/ConfigShowCommandTest.php
`Tempest\Core\Middleware` now stores reflections of middleware classes. This resulted in exception for `./tempest config:show` command.
This fixes that + adds a test to catch such regression.
=> fix(framework): handle reflection in config show command

packages/validation/src/Validator.php, packages/validation/tests/ValidatorTest.php
This pull request adds a new `validateValues` public method to the validator, allowing the validation of an array of values against an array of rules.
```php
$validator->validateValues(
[
'name' => 'Jon Doe',
'email' => 'jon@doe.co',
'age' => 25,
],
[
'name' => [new IsString(), new NotNull()],
'email' => [new Email()],
'age' => [new IsInteger(), new NotNull()],
],
);
```
=> feat(validation): add ability to validate an array of values

packages/router/src/GenericRouter.php, packages/router/src/Router.php, tests/Integration/Route/RouterTest.php
Closes #1182.
Hard-coded uris must now starts with a slash.
I'll add tests after #1186.
This function signature is barebone, do the framework have a stance on external documentation vs docblocks ? I can address this issue in a later PR.
=> fix(router): require hard-coded uris to start with a slash in `Router::toUri`

packages/support/src/Arr/functions.php, packages/support/tests/Arr/FunctionsTest.php
This pull request fixes a typo in the docblocks of `Arr\remove_values` regarding its mutability, and more importantly, actually fixes the mutability of `Arr\forget_values` and `Arr\forget_keys`.
Those two functions were meant to be mutable, and have immutable counterparts (`Arr\remove_values` and `Arr\remove_keys`), but the first argument was not passed as reference.
Tests have been added to cover them.
=> fix(support): make `Arr\forget_values` and `Arr\forget_keys` mutable

packages/support/src/Regex/functions.php
Otherwise, calling `Regex\replace` with `replacement` set to an existing PHP function (eg. `mail`) would call that function. And we don't want that.
=> fix(support): use `Closure` instead of `callable` when calling `preg_replace_callback`

packages/console/src/Schedule.php, packages/console/src/Scheduler/OutputMode.php
We use screaming snake case for our enums, this is a consistency change. Took the opportunity to add some docblocks as well.
=> refactor(console): update `OutputMode` enum casing

packages/database/src/QueryStatements/CreateEnumTypeStatement.php, packages/database/src/QueryStatements/EnumStatement.php, tests/Integration/Database/Fixtures/EnumForCreateTable.php, tests/Integration/Database/QueryStatements/CreateEnumTypeStatementTest.php, tests/Integration/Database/QueryStatements/EnumStatementTest.php
Fixes https://github.com/tempestphp/tempest-framework/issues/963
=> fix(database): prepend backslash when creating enum columns

packages/support/src/Str/functions.php, packages/support/tests/Str/ManipulatesStringTest.php
This pull request improves `to_snake_case` to handle cases like `Application URI` or `HTTPRequest`.
Previously, every uppercase letter would be separated by the delimited (eg. `application_u_r_i` and `h_t_t_p_request`). Now, those are handled correctly as `http_request` and `application_uri`.
=> fix(support): support more `to_snake_case` edge cases

packages/core/src/EnvironmentInsightsProvider.php
Quick follow-up for https://github.com/tempestphp/tempest-framework/pull/1226, which had a logic issue that was making the command display `Composer version 2.0.0` instead of `2.0.0`.
=> fix(core): display clean version in `about` command

packages/database/src/DatabaseInsightsProvider.php, packages/database/tests/DatabaseInsightsProviderTest.php
This PR fixes an issue where the regex patterns used for MySQL and PostgreSQL version insights were swapped. Additionally, it updates the handling of MySQL's VERSION() output, which may include a suffix with server build or configuration details.
=> fix(database): properly display mysql and postgresql versions in `about` command

packages/http/src/HttpException.php, packages/http/src/Responses/ServerError.php, packages/router/src/Exceptions/HttpErrorResponseProcessor.php, packages/router/src/GenericRouter.php, packages/router/src/RouteConfig.php, packages/router/src/Static/StaticGenerateCommand.php, src/Tempest/Framework/Testing/Http/HttpRouterTester.php, tests/Integration/Application/HttpApplicationTest.php, tests/Integration/Http/GenericResponseSenderTest.php, tests/Integration/Route/Fixtures/Http500Controller.php, tests/Integration/Route/RequestTest.php, tests/Integration/Route/RouterTest.php, tests/Integration/Testing/Http/HttpRouterTesterIntegrationTest.php
This pull request is a follow-up to https://github.com/tempestphp/tempest-framework/pull/1203. Previously, I didn't touch the `throwException` method on the router and kept the logic as-is. 
However, that feature in combination with the new exception handling made it that 404s in development would still show a blank page, because `HttpException` would not be thrown (they would only in production).
Instead, I refactored the feature outside of `GenericRouter` into `RouteConfig` as a simple boolean flag, used by the error response processor. With this design, and a small update to the HTTP router testing, we can keep the previous behavior (no exception in testing by default), while having a good UX in development and production (HttpExceptions are properly thrown and handled).
The only thing …
=> refactor(router): improve exception handling

composer.json, mago.toml, packages/console/src/Exceptions/ConsoleExceptionHandler.php, packages/core/src/DevelopmentExceptionHandler.php, packages/core/src/ExceptionHandlerInitializer.php, packages/core/src/ExceptionReporter.php, packages/core/src/ExceptionTester.php, packages/core/src/FrameworkKernel.php, packages/core/src/Kernel/RegisterEmergencyExceptionHandler.php, packages/core/src/functions.php, packages/http/src/HttpException.php, packages/router/src/Exceptions/HttpErrorResponseProcessor.php, packages/router/src/Exceptions/HttpExceptionHandler.php, src/Tempest/Framework/Testing/IntegrationTest.php, tests/Integration/Core/ExceptionReporterTest.php, tests/Integration/Core/ExceptionTesterTest.php, tests/Integration/FrameworkIntegrationTestCase.php, tests/Integration/Http/HttpExceptionHandlerTest.php
This pull request improves on the concept of exception processor by refactoring them into a dedicated `ExceptionReporter` class, which can be used to report exceptions without throwing them, just like Laravel.
Calling the `Tempest\report()` function will call the registered exception processors. Additionally, I added testing utilities that can make assertions on reported exceptions.
Documentation PR: https://github.com/tempestphp/tempest-docs/pull/82
=> feat(core): support exception reporting

packages/command-bus/src/AsyncCommandMiddleware.php, packages/support/composer.json, packages/support/src/Random/functions.php, packages/support/src/Str/ManipulatesString.php, packages/support/tests/Random/FunctionsTest.php, packages/support/tests/Str/ManipulatesStringTest.php, packages/validation/src/Rules/Uuid.php
This pull request adds a `Random\uuid()`, `Random\is_uuid()`, `Random\ulid()` and `Random\is_ulid()` utilities. It also updates our `Uuid` validation rule to use those under the hood, and add them to the string objects as well.
=> feat(support): add uuid utilities

packages/cache/src/Cache.php, packages/cache/src/CacheInitializer.php, packages/cache/src/GenericCache.php, packages/cache/src/Testing/RestrictedCache.php, packages/cache/src/Testing/TestingCache.php, packages/core/src/DeferredTasks.php, packages/core/src/Kernel/FinishDeferredTasks.php, tests/Integration/Cache/CacheTest.php, tests/Integration/Core/DeferredTasksTest.php
This pull request adds support for the "stale while invalidate" pattern on the cache implementation.
```php
$cache->resolve(
key: 'cache-key',
callback: fn () => $this->computeExpensiveValue(),
expiration: Duration::minute(), // should expire in a minute
stale: Duration::minute() // but allow a stale period of one more minute
);
```
When requested in the stale window (in this example, from one minute to two minutes after caching the value), a deferred callback will be registered for refreshing the value.
=> feat(cache): support stale while revalidate

packages/event-bus/src/EventBus.php, packages/event-bus/src/EventBusConfig.php, packages/event-bus/src/GenericEventBus.php, packages/event-bus/src/Testing/FakeEventBus.php, packages/event-bus/src/functions.php, packages/event-bus/tests/EventBusTest.php, packages/http/src/Session/CleanupSessionsCommand.php, packages/reflection/src/FunctionReflector.php, packages/reflection/tests/FunctionReflectorTest.php, packages/router/src/Static/StaticCleanCommand.php, packages/router/src/Static/StaticGenerateCommand.php, tests/Integration/Debug/DebugTest.php, tests/Integration/EventBus/EventBusTesterTest.php, tests/Integration/Log/GenericLoggerTest.php
Closes https://github.com/tempestphp/tempest-framework/issues/1290
As specified in the issue, there was an inconsistency and a DX papercut here. The first parameter was redundant with the closure's signature. 
Instead of removing the `$event` parameter, I reordered it and made it optional, so string-based events could still be supported by this method.
=> fix(event-bus): reorder `listen` parameters for consistency

.gitignore, packages/core/src/FrameworkKernel.php
Closes https://github.com/tempestphp/tempest-framework/issues/1281
Before merging, is `.tempest` the ideal name? Could also be `storage`, `.internal`, or something else. I like a dot directory because it's naturally ignored when scanning the hierarchy, but the name "tempest" is not generic and generally I don't like that
Also, we need to add it to `.gitignore` in `tempestphp/tempest-app`
=> refactor(core): move internal storage to project root

packages/router/src/Commands/ServeCommand.php
Closes #1316
Allows for running `tempest serve host:port`. If `port` in that case is not a valid number, the original `$port` argument is used.
=> feat(router): allow specifying port using `host:port` syntax

bin/release
Closes https://github.com/tempestphp/tempest-framework/issues/898
I couldn't test on Tempest's actual ruleset because I can't create a personal token for it, but I did try it out on one of my repositories and it properly disables/enables the protection.
@brendt You'll need to create a PAT with **admin** permission on `tempestphp/tempest-framework`, and add it to the `.env` of your local clone of the repository as `RELEASE_GITHUB_TOKEN`.
I didn't re-try the full release script with that though, so you'll find out for v1.0.2 :D
=> chore(release): automatically update branch protection during release

packages/core/src/Kernel/LoadDiscoveryClasses.php, packages/discovery/src/DiscoveryLocation.php, packages/mapper/src/Mappers/JsonToArrayMapper.php, tests/Integration/Mapper/MapperTest.php
Instead of relying on `RecursiveDirectoryIterator`, we now manually loop over all directories, giving us an entrypoint to entirely skip specific sub-directories (like `node_modules`). We can improve on this in the future by making it configurable, although for now a hard-coded check is fine. 
Closes #1328
=> chore(core): improve discovery performance by excluding specific directories

packages/core/src/ExceptionProcessor.php, packages/core/src/ExceptionReporter.php, packages/core/src/LogExceptionProcessor.php, tests/Integration/Http/Fixtures/NullExceptionProcessor.php
This pull request updates the `ExceptionProcessor` interface to no longer return an updated throwable, which wasn't taken into account anyway.
=> refactor(core)!: update exception processors to no longer return a throwable

packages/log/src/GenericLogger.php, tests/Integration/Log/GenericLoggerTest.php
This fixes case when someone first logs something at high severity (for example critical) and next by lower severity (debug).
Before, it would cache a Handler with LEVEL set to CRITICAL, and DEBUG log would be ignored.
Now, new handler will be created (and cached).
=> fix(log): fix driver resolving not accounting log level

packages/http/src/Session/Session.php, tests/Integration/Http/FileSessionTest.php
I am building an inertia adapter for tempest and to make it work like the laravel one, I need some way of reflashing when "frontend-asset-mismatch" happens and should reload the page for the user.
The test might not be in the correct location, but I couldn't really find a better place :/
=> feat(session): add reflash method to session

composer.json
This should fix all php deprecation errors related to vlucas/phpdotenv in the tests
=> chore(core): upgrade phpdotenv to remove deprecation warnings

composer.json
The package is loaded via the tempest/blade package anyway so there is no need to add it as an explicit dependency on the root composer.json
=> chore(view): remove unused `illuminate/view`

packages/router/src/GenericRouter.php, packages/router/src/MatchRouteMiddleware.php
This prevents weird edge cases when the normal request flow is interrupted before `MatchRouteMiddleware` has run, but still a response is sent (which depends on the request)
=> fix(http): register request interface as singleton as soon as possible

packages/database/src/Casters/IdCaster.php, packages/database/src/DatabaseInitializer.php, packages/database/src/GenericDatabase.php, packages/database/src/Serializers/IdSerializer.php, packages/database/src/Serializers/IdSerializerProvider.php, packages/database/tests/GenericDatabaseTest.php, packages/mapper/src/Mappers/ObjectToArrayMapper.php, packages/mapper/src/SerializerFactory.php, packages/mapper/src/SerializerFactoryInitializer.php, packages/mapper/src/Serializers/DateTimeSerializer.php, packages/mapper/src/Serializers/NativeDateTimeSerializer.php, tests/Integration/Mapper/MapperTest.php, tests/Integration/Mapper/SerializerFactoryTest.php, tests/Integration/Mapper/Serializers/ArrayOfObjectsSerializerTest.php, tests/Integration/Mapper/Serializers/DateTimeSerializerTest.php, tests/Integration/ORM/IsDatabaseModelTest.php, tests/Integration/ORM/Migrations/CreateDateTimeModelTable.php, tests/Integration/ORM/Models/DateTimeModel.php, tests/Integration/TestingDatabaseInitializer.php
Closes https://github.com/tempestphp/tempest-framework/issues/1345
=> fix(database): fix datetime serialization for mysql database

src/Tempest/Framework/Commands/MigrateFreshCommand.php, tests/Integration/Framework/Commands/MigrateFreshCommandTest.php
=> feat(database): run `migrate:fresh` without validation by default

packages/view/src/Elements/TextElement.php, packages/view/src/Parser/TempestViewCompiler.php, tests/Integration/View/TempestViewRendererTest.php
Fixes https://github.com/tempestphp/tempest-framework/pull/1356#issuecomment-3044774418
Closes https://github.com/tempestphp/tempest-framework/issues/1376
=> fix(view): remove multiline comments before AST parsing

packages/support/src/Arr/ManipulatesArray.php, packages/support/src/Str/ManipulatesString.php, packages/support/tests/Arr/ManipulatesArrayTest.php, packages/support/tests/Str/ManipulatesStringTest.php
Closes https://github.com/tempestphp/tempest-framework/issues/1388
=> feat(support): add json encode/decode to array and string utilities

packages/vite-plugin-tempest/src/plugin.ts, packages/vite/src/TagsResolver/DevelopmentTagsResolver.php, packages/vite/src/Vite.php, packages/vite/src/ViteBridgeFile.php, tests/Integration/Vite/ViteTagsComponentTest.php
Using the vite react plugins requires this snippet to be present:
> Note if you are using React with @vitejs/plugin-react, you'll also need to add this before the above scripts, since the plugin  is not able to modify the HTML you are serving (substitute http://localhost:5173 with the local URL Vite is running at):
>```html 
> <script type="module">
>  import RefreshRuntime from 'http://localhost:5173/@react-refresh'
>  RefreshRuntime.injectIntoGlobalHook(window)
>  window.$RefreshReg$ = () => {}
>  window.$RefreshSig$ = () => (type) => type
>  window.__vite_plugin_react_preamble_installed__ = true
></script>
>```
This PR adds so the vite plugin detects if this needs to be injected, adds a bool to the bridgefile that the `DevelopmentTagsResolver` reads and injects the "snippet".
One …
=> feat(vite): inject react refresh when needed

packages/http/src/Session/CsrfTokenComponent.php, packages/http/src/Session/CsrfTokenDidNotMatch.php, packages/http/src/Session/Session.php, packages/http/src/Session/VerifyCsrfMiddleware.php, packages/router/src/Exceptions/HttpExceptionHandler.php, tests/Integration/Http/CsrfTest.php, tests/Integration/Http/HttpExceptionHandlerTest.php
This pull request introduces support for cross-site request forgery protection. This is a pretty important feature to have, so it will be enabled by default. Technically, this is thus a breaking change.
Non-read requests now require a CSRF token to be present. It can be a `_token` in the request body or in a `x-xsrf-token` header. All requests will return the CSRF token in a `xsrf-token` cookie. This pattern is standard across AJAX clients, which means there is no particular setup needed for them.
For standard HTML forms, a `<x-csrf-token />` component is available. It renders a hidden `_token` input. Otherwise, the token is available as the `token` property of `Tempest\Http\Session`.
Note that after https://github.com/tempestphp/tempest-framework/pull/1346, we might iterate on this so …
=> feat(http)!: add cross-site request forgery protection

composer.json, packages/http/composer.json, packages/http/src/Cookie/Cookie.php, packages/http/src/Cookie/CookieManager.php, packages/http/src/Session/CsrfTokenComponent.php, packages/http/src/Session/VerifyCsrfMiddleware.php, packages/http/src/Session/x-csrf-token.view.php, packages/http/src/functions.php, tests/Integration/Http/CookieManagerTest.php, tests/Integration/Http/CsrfTest.php
This pull request:
- reverts `x-csrf-token` to a view component
- introduces a `csrf_token()` function that's a shorthand for accessing the `token` property of `Session`
- makes the CSRF cookie secure
- slightly refactor the `Cookie` class
=> feat(http): add `csrf_token` function

packages/http/src/Cookie/CookieManager.php, packages/http/src/Cookie/CookieManagerInitializer.php, packages/http/src/Input/StdinInputStream.php, packages/http/src/IsRequest.php, packages/http/src/Mappers/PsrRequestToGenericRequestMapper.php, packages/http/src/Session/Config/FileSessionConfig.php, packages/http/src/Session/Resolvers/CookieSessionIdResolver.php, packages/http/src/Session/Session.php, packages/http/src/Session/SessionConfig.php, packages/http/src/Session/SessionIdResolverInitializer.php, packages/http/src/Session/VerifyCsrfMiddleware.php, packages/router/src/GenericResponseSender.php, packages/router/src/SetCookieMiddleware.php, tests/Integration/Http/CookieManagerTest.php, tests/Integration/Http/CsrfTest.php, tests/Integration/Http/SessionFromCookieTest.php, tests/Integration/Http/SessionFromHeaderTest.php, tests/Integration/Mapper/PsrRequestToRequestMapperTest.php
This pull request fixes our cookie handling.
Previously, the `CookieManager` was instantiated with all cookies sent by the client (from `$_COOKIE`), and was also used to send back cookies to the client (using `Set-Cookie`). Now, cookies sent by the client are defined on the `Request` class only, and the cookie manager is only used for managing cookies that are going to be sent to the client.
Additionally, this pull request fixes an important issue with sending headers to the client, where sending a header would replace a previously-set header with the same name, preventing from sending multiple `Set-Cookie` headers, notably.
Last, there is some minor clean-up and I added some docblocks on confusing classes and methods.
=> fix(http): properly handle cookies lifecycle

packages/mapper/src/CasterFactoryInitializer.php, packages/mapper/src/Casters/BooleanCaster.php, packages/mapper/src/Casters/EnumCaster.php, packages/mapper/src/SerializerFactoryInitializer.php, tests/Integration/Mapper/CasterFactoryTest.php, tests/Integration/Mapper/Casters/BooleanCasterTest.php, tests/Integration/Mapper/Casters/EnumCasterTest.php, tests/Integration/Mapper/Fixtures/ObjectWithSerializerProperties.php, tests/Integration/Mapper/Mappers/ArrayToObjectMapperTestCase.php, tests/Integration/Mapper/Serializers/ArrayOfObjectsSerializerTest.php
This pull request fixes casting of `bool`, `int`, `float` and backed/unit enums, as well as serializing unit enums.
I first discovered missing support for this when creating a request class with a boolean property, which was always set to true (because the `false` in the query was a string).
=> fix(mapper): support casting `bool`, `int`, `float` and enums

packages/vite/src/TagsResolver/ManifestTagsResolver.php
This PR prevents two potential runtime errors in the browser:
1. An `Uncaught SyntaxError: Unexpected token ']'` when no assets are available to prefetch.
2. An `Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')` when the page's assets are minified.
**Prevent empty prefetch script injection:**
`resolvePrefetchingScript` now returns early if the list of prefetchable assets is empty, preventing the `SyntaxError`.
**Prevent JS TypeError on minification:**
Added a terminating semicolon to the `new DocumentFragment()` instantiation within the `AGGRESSIVE` strategy's script template to ensure correct statement separation after minification, preventing the `TypeError`.
I believe the fixes are straightforward enough not to require dedicated test cases, but I'm happy to …
=> fix(vite): prevent syntax errors on prefetching script

packages/view/src/Elements/ViewComponentElement.php, packages/view/src/Export/ExportableViewObject.php, packages/view/src/Export/ViewObjectExporter.php, packages/view/src/Slot.php
Including the content of dynamic slots in the template using normal `var_export` can cause compiler errors because `var_export` doesn't properly escape quoted strings within exported values.
To work around that, I added a new `\Tempest\View\Export\ViewObjectExporter` that exports objects to valid PHP code.
For now, this exporter is very hard-coded towards this one specific use-case for exporting slots. We might refactor it in the future to be something reusable, and maybe even integrate it with the mapper (something like `map($object)->toPhp()`, but that's out of scope for now.)
=> refactor(view): improve slot importing to prevent view compiler failures

packages/datetime/src/DateTime.php, packages/datetime/src/DateTimeConvenienceMethods.php, packages/datetime/src/DateTimeInterface.php, packages/datetime/src/TemporalConvenienceMethods.php, packages/datetime/src/TemporalInterface.php, packages/datetime/tests/DateTimeTest.php, packages/datetime/tests/TimestampTest.php
This pull request adds many convenience methods to the `DateTime` and `Timestamp` classes. It was a bit of work so I procrastinated that, but we have them now!
```php
$date->isToday();
$date->isSameDay($otherDate);
$date->isEndOfWeek();
$date->isLastDayOfYear();
```
=> feat(datetime): add convenience comparison and manipulation methods

packages/view/src/Components/x-base.view.php
To avoid this warning in console : This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
=> fix(view): set doctype in `x-base`

packages/database/src/QueryStatements/CreateTableStatement.php, tests/Integration/Database/ModelWithDtoTest.php, tests/Integration/Database/QueryStatements/CreateTableStatementTest.php
This pull request is a minor quality of life regarding the creation of tables. I added a `string` method to create a `VARCHAR` column (as an alias to the existing `varchar` method). 
I also renamed `dto` to `object`, because `dto` is very generic. I'm also considering renaming `DtoCaster` and `DtoSerializer` in another PR, let me know.
And last, I added comments for each method to give a little more context to developers. :)
=> feat(database): add `string` method on `CreateTableStatement`

packages/http/src/ServerSentEvent.php, packages/http/src/ServerSentMessage.php, packages/router/src/GenericResponseSender.php, tests/Integration/Http/GenericResponseSenderTest.php
The current implementation of the `GenericResponseSender` hardcoded the server sent event protocoll to:
```php
echo "event: {$event}\n";
echo "data: {$data}";
echo "\n\n";
```
We cannot use multiple data lines or add something like `id` or `retry` to the fields list https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#fields.
I introduced a Interface `ServerSentEvent` with a hooked property `$datalines` to move the shape of the data transmitted with a single message into the Event itself.
This change allows us to implement the datastar protocoll for example:
```txt
event: datastar-patch-elements
data: elements <div id="hal">
data: elements     I’m sorry, Dave. I’m afraid I can’t do that.
data: elements </div>
```
=> feat(http): offer more control over server sent events format

packages/http/src/Mappers/PsrRequestToGenericRequestMapper.php, tests/Integration/Mapper/PsrRequestToRequestMapperTest.php
If you send request
```json
{
"body": "hello world"
}
```
it will treat request body as `hello world`, but it should be `['body' => 'hello world']`
I think this splat operator have no meaning here? Eventually it could be
```php
[
...$body,
'body' => $data,
]
```
=> fix(mapper): don't overwrite request fields

packages/core/src/Kernel/LoadConfig.php
The vendor directory is string matched to give it the lowest priority when loading configuration files during discovery. This change sets the prefixed and suffixed directory separator to the PHP constant DIRECTORY_SEPARATOR rather than hard-coding '/'. This allows the match to work when PHP is running on Windows (which uses '\' as a directory separator), as well as on other platforms.
Resolves tempestphp/tempest-framework#1526
=> fix(core): discover vendor directory first on all platforms

docs/1-essentials/01-routing.md, docs/4-internals/03-view-spec.md, packages/router/src/GenericRouter.php, packages/router/src/Router.php, packages/router/src/Static/StaticGenerateCommand.php, packages/router/src/UriGenerator.php, packages/router/src/functions.php, tests/Fixtures/Controllers/ValidationController.php, tests/Fixtures/Modules/Books/BookController.php, tests/Fixtures/Modules/Form/form.view.php, tests/Fixtures/Views/button-usage.view.php, tests/Fixtures/Views/x-view-component-with-use-import.view.php, tests/Fixtures/x-with-header.view.php, tests/Integration/Auth/AuthorizerTest.php, tests/Integration/Core/DeferredTasksTest.php, tests/Integration/Http/Static/Fixtures/StaticPageController.php, tests/Integration/Http/ValidationResponseTest.php, tests/Integration/Http/ViewDataTest.php, tests/Integration/Route/RequestTest.php, tests/Integration/Route/RouterTest.php, tests/Integration/Route/UriGeneratorTest.php, tests/Integration/View/TempestViewRendererTest.php, tests/Integration/View/ViewTest.php
This pull request adds support for signed URIs. Additionally, it moves the URI generation methods from the `Router` interface to their own dedicated `UriGenerator` class.
Generating signed URIs can be done with their dedicated functions:
```php
use function Tempest\signed_uri;
use function Tempest\temporary_signed_uri;
// unsubscribe link
signed_uri(
action: [MailingListController::class, 'unsubscribe'],
email: $email
);
// magic login link
temporary_signed_uri(
action: PasswordlessAuthenticationController::class,
duration: Duration::minutes(10),
userId: $userId
);
```
To ensure a signature is valid, the `hasValidSignature` method should be called on the UriGenerator` class:
```php
final class PasswordlessAuthenticationController
{
public function __construct(
private readonly …
```
=> feat(router)!: support signed URIs

packages/database/src/Migrations/RunnableMigrations.php, packages/database/tests/Migrations/RunnableMigrationsTest.php
Fixes https://github.com/tempestphp/tempest-framework/issues/1539
=> fix(database): ensure natural ordering for migrations

mago.toml, packages/console/src/Components/Renderers/TextInputRenderer.php, packages/database/src/Mappers/SelectModelMapper.php, packages/mapper/src/Mappers/ArrayToObjectMapper.php, packages/support/src/Str/functions.php, packages/view/src/Elements/PhpDataElement.php, tests/Integration/Database/Builder/IsDatabaseModelTest.php, tests/Integration/Database/MultiDatabaseTest.php
=> fix(database): nullable belongsto relations

packages/database/src/Testing/DatabaseTester.php, src/Tempest/Framework/Testing/IntegrationTest.php, tests/Integration/Database/Testing/DatabaseTesterTest.php, tests/Integration/FrameworkIntegrationTestCase.php
This pull request adds database testing utilities, such as `assertTableHasRow`, `assertTableHasCount`, `assertTableDoesNotHaveRow`, `assertTableEmpty`, and `assertTableNotEmpty`.
Previously, there was our base test case had a `setupDatabase`, `migrateDatabase` and `migrate` methods. They still exists, but are now deprecated in favor of the ones in the new `DatabaseTester` class.
The behavior is different as well:
- The `setupDatabase` method is now `reset` (with a `setup` alias), and migrates *all registered migrations*. You can set the `migrate` argument to `false` to not migrate anything.
- The `migrate` method migrates all registered migrations if no specific migration is provided.
- I removed `migrateDatabase`.
Additionally, discovery is now configured to scan `tests` instead of …
=> feat(database): add testing utilities

src/Tempest/Framework/Testing/Http/HttpRouterTester.php, src/Tempest/Framework/Testing/Http/TestResponseHelper.php, tests/Integration/Testing/Http/HttpRouterTesterIntegrationTest.php, tests/Integration/Testing/Http/TestResponseHelperTest.php
This pull request adds a `$query` parameter to route testing utils, which allows to do this:
```php
$this->http
->get("/oauth/discord/callback", query: [
'code' => 'some-fake-code',
'state' => $oauth->getState(),
])
->assertRedirect();
```
Instead of having to do this:
```php
$this->http
->get("/oauth/discord/callback?code=some-fake-code&state={$oauth->getState()}")
->assertRedirect();
```
=> feat(http)!: add `query` parameter to route testing utilities

packages/database/src/Builder/ModelInspector.php, tests/Fixtures/Migrations/CreateProfileWithEagerTable.php, tests/Fixtures/Migrations/CreateUserWithEagerTable.php, tests/Fixtures/Models/ProfileWithEager.php, tests/Fixtures/Models/UserWithEager.php, tests/Integration/Database/CircularEagerLoadingTest.php
Modified `ModelInspector` to track visited model types and prevent infinite recursion:
* Tracking visited model types in an array as we traverse the relationship tree
* Before recursing into a relation, check if the target model type is already in the visited path
* If a circular reference is detected, skip that relation to prevent infinite recursion
* Passing the updated visited paths array to recursive calls
Fixes #1494
=> fix(database): handle loading circular eager relations

docs/1-essentials/01-routing.md, packages/database/src/Builder/QueryBuilders/HasConvenientWhereMethods.php, packages/http/src/Session/CleanupSessionsCommand.php, packages/http/src/Session/Config/DatabaseSessionConfig.php, packages/http/src/Session/Config/FileSessionConfig.php, packages/http/src/Session/Config/session.config.php, packages/http/src/Session/Installer/CreateSessionsTable.php, packages/http/src/Session/Installer/DatabaseSessionInstaller.php, packages/http/src/Session/Installer/session.config.stub.php, packages/http/src/Session/Managers/DatabaseSession.php, packages/http/src/Session/Managers/DatabaseSessionManager.php, packages/http/src/Session/Session.php, packages/http/src/Session/SessionConfig.php, tests/Integration/Http/DatabaseSessionTest.php, tests/Integration/Http/FileSessionTest.php
This pull request introduces support for database-based sessions. It works by providing a migration file through an installer, a new configuration file, and a built-in database session manager.
The installer publishes the migration file and a `session.config.php` with the following contents:
```php
use Tempest\Http\Session\Config\DatabaseSessionConfig;
use Tempest\DateTime\Duration;
return new DatabaseSessionConfig(
expiration: Duration::days(30),
);
```
Note that even though the migration is published, it should not be modified, because the database session manager expects the exact columns defined on it. Unfortunately, I don't see a good way to publish the implementation itself without it feeling out of place.
I also fixed an issue with the existing file-based implementation: sessions …
=> feat(http): support database-based sessions

docs/0-getting-started/02-installation.md
I think i found the correct target link to jump to.
(Btw: I also stumbled over the SIGNING_KEY error on first temptest installation. But i found the solution on discord by Innocenzi: https://discord.com/channels/1236153076688359495/1236153079603269766/1423353262903529552.)
=> docs: fix vite install docs link for running dev server

docs/1-essentials/01-routing.md
I just noticed that the x-error view component snippet is not working when i tried to implement my own x-error view component.
This PR updates the snippet so it now uses the validator to fetch the error message.
=> docs(routing): fix x-error view component snippet
